### ISSUE TITLE
Crossref client timeout is not set

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#108]
Python `urllib2` defaults to the ["global default timeout setting"](global default timeout setting) which is [∞](https://stackoverflow.com/questions/29649173/what-is-the-global-default-timeout).

A reasonable timeout should be set as a floating point value in seconds. 30 sec is a common choice for this type of operation.

The setting needs to appear in [crossref.py 304](https://github.com/CDLUC3/ezid/blob/master/impl/crossref.py#L304) and [361](https://github.com/CDLUC3/ezid/blob/master/impl/crossref.py#L361), though should be specified in an appropriate configuration location.

Other uses of urlopen and other socket type connections should be examined for appropriate timeout configuration.

This issue is more pervasive than apparent at first pass. Since unreleased connections seem to be a rare issue, suggest deferring this fix to the Python3 stream. As part of the fix, use of a higher level HTTP library (e.g. requests) should be considered to reduce code maintenance and promote protocol compatibility.

**Comment by mariagould** [comment]
@rushirajnenuji can this be incorporated into the latest stage release with the DataCite schema update?
