### ISSUE TITLE
ezid-search2-stg burst balance credits issue reported

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#123]
From 3am-9am RDS notifications were sent to alert of low gp2 burst balance credits.  This can be seen in the Libratro metrics.

https://metrics.librato.com/s/public/azpakcmwd?duration=43200&source=%2Ards-ias-ezid-search%2A-stg%2A

SourceId: rds-ias-ezid-search2-stg
Notification time : 2021-04-28 12:58:43.792
Message : The gp2 burst balance credits for the RDS database instance are low. To resolve this issue, reduce IOPS usage or modify your storage settings to enable higher performance.

Review of logs on stage did not indicate any applicable activity.  It was inconclusive as to what caused this issue.  Rushi reported minting a few identifiers, but this didn't seem related or type of activity that would utilize IOPs to this effect.

This github issue is to track and reference if we see this again.

**Comment by marisastrong** [comment]
These notifications have continued and seem to arrive from 1:59am until 8:59am, whereas they stop. 
Wondering what processing might be occurring during that time to trigger the notification.

**Comment by mariagould** [comment]
Closing for now as we changed the provisioning of the RDS instance (Python 2 stage) so we are no longer receiving the notifications.
