### ISSUE TITLE
Github housekeeping 

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#127]
(1) Rename master branch to main
To be in line with Github's new practice of renaming default branch from master and to support fostering a more inclusive workplace culture, we should rename our master branches to main (or another desired name).  

More information on this can be found here: 
[Easy to rename a branch](https://github.com/github/renaming#rename-existing)
[Renaming the default branch from master](https://github.com/github/renaming)

(2) Remove obsolete branches

**Comment by datadavev** [comment]
Un-merged branches were removed, `ezid-py3` renamed to `main`, and `main` set to the default branch.

`develop` branch created, which should be used for future dev and test work. Merge to `main` when work is complete. `main` should always reflect runnable code.
