### ISSUE TITLE
Deploy EZID dev instance on EC2

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#13]
This will result in a test instance of EZID that operates entirely independently of N2T for shoulder creation and identifier minting

**Comment by marisastrong** [comment]
Tracking via Pivotal tracker to provision an EC2 instance - https://www.pivotaltracker.com/story/show/172301210

**Comment by ashleygould** [comment]
action items for ashley:

- request SSL certs for uc3-ezidx2-dev
- create puppet config for uc3-ezidx2-dev to manage apache
- follow up on port 80/443 redirect practices with IAS
- request ssh access for Dave and Roger to uc3-ezidx2-stg host
