### ISSUE TITLE
Resolve high-severity security alerts

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#15]
Github is reporting a number of security alerts for UI components of EZID:

https://github.com/CDLUC3/ezid/network/alerts

These all need to be reviewed and addressed as needed.

**Comment by mariagould** [comment]
Test on stage first and then push to production.

**Comment by rushirajnenuji** [comment]
**Sprint August 18, 2020**: Include working changes on a separate branch. Test the branch on stage and cut a tag. 
Should only include changes that fix these security updates. We'll be deprecating [this EZID UI repo](https://github.com/cdlib/ezid-ui), and keep building UI features from this codebase. 
Note: We'll still be keeping t[he info pages repository](https://github.com/CDLUC3/ezid-info-pages) as-is.

**Comment by mariagould** [comment]
@rushirajnenuji to see if Dependabot can look at other branches

**Comment by mariagould** [comment]
We'll see what happens after we merge to master. May need to be addressed with future Python 3 work

**Comment by marisastrong** [comment]
I have disabled dependabot security updates to prevent further pull requests from being created.

However dependabot will continue to report and inform us of security vulnerabilities in the code. 

https://docs.github.com/en/code-security/supply-chain-security/about-dependabot-security-updates

**Comment by marisastrong** [comment]
https://github.com/CDLUC3/ezid/security/dependabot/package-lock.json/underscore/open

we should review what other high severity alerts we have received.

**Comment by datadavev** [comment]
This will likely be resolved when merged with master

**Comment by marisastrong** [comment]
now that we have renamed py3 branch to main, hoping some of the dependabot alerts go away.  They haven't yet and now a few more have cropped up.  I wonder if we need to manually indicate that earlier alerts are no longer an issue; trigger a new dependabot scan manually or configure with a dependabot.yaml config file.  

[Configuring Dependabot security updates ](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories)
