### ISSUE TITLE
Intermittent 502 bad gateway occurs with large batch Merritt ingests

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/ezid#161]
During the course of processing large batches of content, Merritt will occasionally receive a "502 bad gateway" error when attempting to mint an ARK using EZID. To lend a sense of frequency, UC Berkeley Library recently sent seven batches of 10K objects each. During three of these submissions, 1-2 minting errors occurred which prevented ingestion of the associated objects.

Here is the error reported via our Ingest service, which basically bubbles up the 502:
```
Status message: [error]: HandlerMinter: error in minting identifier: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
``` 

Submission timestamps for two of the errors, in case these are helpful:
2021-10-14T08:45:05-07:00
2021-10-16T07:08:45-07:00

Merritt's ingest service currently retries three times in cases where it does not receive an immediate response from EZID. We will be augmenting this to retry 5 times, with intervals of up to 30 seconds:
https://github.com/CDLUC3/mrt-doc/issues/837

Please investigate, and let us know if you need any additional information. Thanks!

**Comment by marisastrong** [comment]
Merritt is experiencing 502 Bad Gateway errors.  Reopening this ticket to do some investigation of the effort.  Mark is out on vacation and won't be able to assist in reproducing the problem, but when the problem happens, Merritt team will try to provide a timestamp to assist with checking the logs.

**Comment by jsjiang** [comment]
@mreyescdl Thank you Mark for reporting the 502 error. I will take a look form the ezid side.  -Jing

**Comment by jsjiang** [comment]
@mreyescdl I cannot find any 502 error in the ELB log file. Do you have the IDs for the failed items?  Jing

**Comment by mreyescdl** [comment]
Thanks for looking into this @jsjiang 

It turns out that there are only 2 EZID 502s.  The third 502 is from our Inventory service.
Here are the requests:
```
jid-037d5d82-88f2-49d5-a757-91d1ae80f025 - Ingest 02
2023-07-14 07:53:34
        [info] MintUtil: response code: 502
        [info] MintUtil: response phrase: Bad Gateway
        [info] MintUtil: could not update, attempting to create: https://ezid.cdlib.org/id/ark:/13030/m513514t


jid-277633b6-adce-4bd7-bf9e-a812c722b68e - Ingest 01
2023-07-13 18:56:07
        [info] MintUtil: response code: 502
        [info] MintUtil: response phrase: Bad Gateway
        [info] MintUtil: could not update, attempting to create: https://ezid.cdlib.org/id/ark:/13030/m5v78q7d
```

**Comment by jsjiang** [comment]
What I found:
* EZID generated duplicated requests for these createIdentifier requests within very short time period on two different session IDs.
* No abnormal activities on the EZID-prd EC2 and RDS instances;
* These requests were logged with error code 400 and 401 on the ELB; no 502 errors were found for these identifiers.

**Comment by mreyescdl** [comment]
Thanks for the analysis @jsjiang 

I too could not find the 502 error in our Inventory ALB logs.  I suspect that these errors are not logged by AWS ALBs.

We had 4 more 502s over the weekend during large submission and I suspect that it may be an issue with the ALB under load.
Is it okay if I try and trigger a 502 error on your stage instance? ( ezid-stg.cdlib.org )

**Comment by jsjiang** [comment]
Next steps:

1. Review Apache logs
2. Review EC2 Librato metics
3. Find out if duplicated createIdentifier requests also occurred to other accounts beside Merritt
4. Work with AWS support to find out whey 502 error code was not logged on ELB

**Comment by jsjiang** [comment]
1. Apache log: 
* No error entries for  7/13, 18:56 and 7/14 7:53
* two entries for each items in  the ezid access log (ezid_access.log-20230715)

```
cat ezid_access.log-20230715 | grep "13/Jul/2023:18:56" | grep "13030/m5v78q7d"
172.30.4.157 - - [13/Jul/2023:18:56:07 -0700] "PUT /id/ark:/13030/m5v78q7d HTTP/1.1" 401 19 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_372)"
172.30.4.157 - - [13/Jul/2023:18:56:07 -0700] "PUT /id/ark:/13030/m5v78q7d HTTP/1.1" 400 46 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_372)"

cat ezid_access.log-20230715 |  grep "14/Jul/2023:07:53" | grep "13030/m513514t"
172.30.45.138 - - [14/Jul/2023:07:53:34 -0700] "PUT /id/ark:/13030/m513514t HTTP/1.1" 401 19 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_372)"
172.30.45.138 - - [14/Jul/2023:07:53:34 -0700] "PUT /id/ark:/13030/m513514t HTTP/1.1" 400 46 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_372)"
```

**Comment by jsjiang** [comment]
Application log  shows the createIdentifier requests were on the same ID but slightly different metadata. The 2nd request had additional metadata for _target. The 2nd request should use POST instead of PUT to update the record.

Item  m5v78q7d:
```
2023-07-13 18:56:06,577 INFO log.begin:133: 9890abc621e911ee955506a406a5cd13 BEGIN createIdentifier normalizedIdentifier="ark:/13030/m5v78q7d" user.username="merritt" user.pid="ark:/99166/p9td9n725" user.group.groupname="merritt" user.group.pid="ark:/99166/p9pn8xd8d" metadata="erc=who:%20UC/JEPS%20Herbaria%0Awhat:%20Ceratodon%20purpureus%20(Hedw.)%20Brid.%20/%20Bryophytes%20/%20%20/%20%20/%2019564533-00b7-47a3-968c-a541c66fd30d%20(Symbiota%20GUID)%0Awhere:%20UC1730854.TIF,mrt.creator=ucjeps_img_archive"
2023-07-13 18:56:06,594 INFO log.success:152: 9890abc621e911ee955506a406a5cd13 END SUCCESS 
2023-07-13 18:56:06,890 INFO log.begin:133: 98c057fe21e911ee955506a406a5cd13 BEGIN setMetadata ark:/13030/m50096sk merritt ark:/99166/p9td9n725 merritt ark:/99166/p9pn8xd8d erc who:%20UC/JEPS%20Herbaria%0Awhat:%20Dendroalsia%20abietina%20(Hook.)%20E.%20Britton%20/%20Bryophytes%20/%20%20/%20%20/%20be524b04-1dfc-4fa1-a96f-c218430e8199%20(Symbiota%20GUID)%0Awhere:%20ark:/13030/m50096sk%0Awhere:%20UC1631693.TIF mrt.creator ucjeps_img_archive _target http://merritt-aws.cdlib.org/m/ark%253A%252F13030%252Fm50096sk
2023-07-13 18:56:06,907 INFO log.success:152: 98c057fe21e911ee955506a406a5cd13 END SUCCESS 
2023-07-13 18:56:07,296 INFO log.begin:133: 98fe469021e911ee955506a406a5cd13 BEGIN createIdentifier normalizedIdentifier="ark:/13030/m5v78q7d" user.username="merritt" user.pid="ark:/99166/p9td9n725" user.group.groupname="merritt" user.group.pid="ark:/99166/p9pn8xd8d" metadata="erc=who:%20UC/JEPS%20Herbaria%0Awhat:%20Ceratodon%20purpureus%20(Hedw.)%20Brid.%20/%20Bryophytes%20/%20%20/%20%20/%2019564533-00b7-47a3-968c-a541c66fd30d%20(Symbiota%20GUID)%0Awhere:%20ark:/13030/m5v78q7d%0Awhere:%20UC1730854.TIF,mrt.creator=ucjeps_img_archive,_target=http://merritt-aws.cdlib.org/m/ark%253A%252F13030%252Fm5v78q7d"
2023-07-13 18:56:07,306 ERROR ezid.createIdentifier:298: (1062, "Duplicate entry 'ark:/13030/m5v78q7d' for key 'ezidapp_identifier.identifier'")
2023-07-13 18:56:07,307 ERROR log.badRequest:164: 98fe469021e911ee955506a406a5cd13 END BADREQUEST
```

Item m513514t
```
2023-07-14 07:53:33,802 INFO log.begin:133: 347a3946225611ee972c06a406a5cd13 BEGIN mintIdentifier ark:/13030/m5 merritt ark:/99166/p9td9n725 merritt ark:/99166/p9pn8xd8d
2023-07-14 07:53:33,811 INFO log.success:152: 347a3946225611ee972c06a406a5cd13 END SUCCESS ark:/13030/m513514t
2023-07-14 07:53:33,811 INFO log.begin:133: 347ba98e225611ee972c06a406a5cd13 BEGIN createIdentifier normalizedIdentifier="ark:/13030/m513514t" user.username="merritt" user.pid="ark:/99166/p9td9n725" user.group.groupname="merritt" user.group.pid="ark:/99166/p9pn8xd8d" metadata="erc=who:%20UC/JEPS%20Herbaria%0Awhat:%20Leptodictyum%20riparium%20(Hedw.)%20Warnst.%20/%20Bryophytes%20/%20%20/%20%20/%2075ba4837-3576-4656-8736-3fd04c4dc82e%20(Symbiota%20GUID)%0Awhere:%20UC1768905.TIF,mrt.creator=ucjeps_img_archive"
2023-07-14 07:53:33,826 INFO log.success:152: 347ba98e225611ee972c06a406a5cd13 END SUCCESS 
2023-07-14 07:53:34,618 INFO log.begin:133: 34f6da32225611ee972c06a406a5cd13 BEGIN createIdentifier normalizedIdentifier="ark:/13030/m513514t" user.username="merritt" user.pid="ark:/99166/p9td9n725" user.group.groupname="merritt" user.group.pid="ark:/99166/p9pn8xd8d" metadata="erc=who:%20UC/JEPS%20Herbaria%0Awhat:%20Leptodictyum%20riparium%20(Hedw.)%20Warnst.%20/%20Bryophytes%20/%20%20/%20%20/%2075ba4837-3576-4656-8736-3fd04c4dc82e%20(Symbiota%20GUID)%0Awhere:%20ark:/13030/m513514t%0Awhere:%20UC1768905.TIF,mrt.creator=ucjeps_img_archive,_target=http://merritt-aws.cdlib.org/m/ark%253A%252F13030%252Fm513514t"
2023-07-14 07:53:34,627 ERROR ezid.createIdentifier:298: (1062, "Duplicate entry 'ark:/13030/m513514t' for key 'ezidapp_identifier.identifier'")
2023-07-14 07:53:34,627 ERROR log.badRequest:164: 34f6da32225611ee972c06a406a5cd13 END BADREQUEST
```

**Comment by jsjiang** [comment]
@mreyescdl Hi Mark,
The error might have come from Merritt. The minting and registration process should be:
1. Mint an ARK ID
2. Create an identifier with initial metadata. This step is no-repeatable
3. Update an identifier with updated metadata. This step is repeatable 

The items ended with 502 errors all called step 2 twice. Can you take a look from Merritt side.
Let me know if you need more information.

Thank you

Jing

**Comment by mreyescdl** [comment]
@jsjiang Thanks for the great analysis.  It is good to attack this issue from client and server-side.

More and more I think that this is not an application issue but an ALB one.
First, there is logic in our EZID client to first attempt to update a EZID id and if this fails, then it attempts to create one.
I would expect you to see the following.
```
POST /id/ark:/13030/m5v78q7d
PUT /id/ark:/13030/m5v78q7d
```
However, you are seeing the first request fail with a 401 error.  I'm not sure why the request would be Unauthorized.

Anyway, back to the ALB.
When we receive the 502 error from the ALB it turns out that the request was actually honored by EZID.
For example at `Tue Jul 18 02:11:20 PDT 2023` we received a 502 error from EZID for a request to update ` https://ezid.cdlib.org/id/ark:/13030/m5fc4q9f`
However, examining EZID record...
```
$ curl https://ezid.cdlib.org/id/ark:/13030/m5fc4q9f
success: ark:/13030/m5fc4q9f
erc: who: UC/JEPS Herbaria%0Awhat: Schizaea elegans (Vahl) Sw. / Pteridophytes /  /  / F (Project Code)%0Awhere: UC1978323.TIF
mrt.creator: ucjeps_img_archive
_owner: merritt
_ownergroup: merritt
_created: 1689671479
_updated: 1689671479
_profile: erc
_target: https://ezid.cdlib.org/id/ark:/13030/m5fc4q9f
_status: public
_export: yes
```

This shows that the record was created at UNIX time `1689671479` which is `Tue Jul 18 2023 02:11:19 GMT-0700 (Pacific Daylight Time)`

This leads me to believe that it is the ALB responding to the request with an inaccurate return code.  I asked Ashley what the `IDLE CONNECTION TIMEOUT` for the EZID ALB and she says 60 seconds.  Is it possible that it is taking longer that this to service a request?

We (Merritt) are starting to see 502 errors in our Inventory ALB as well.
I'll continue to investigate this issue.

Thanks

**Comment by jsjiang** [comment]
@mreyescdl Hi Mark,
In the [ELB log](https://search-os-uc3-logging-stg-suwz42vownvyte6ivqazeifz44.us-west-2.es.amazonaws.com/_dashboards/goto/216f71045f566449e36cf2613fcce205?security_tenant=global) I see 2 GETs and 2 PUTs for 'm5v78q7d' on 7/13. The 2 GETs one from http://storage.cdlib.org:35121/ and one from http://inventory.cdlib.org:36121/. Should the first one perform PUT and the 2nd one perform POST? Also, the metadata for these two requests are slightly different in the EZID application log. The  2nd one has the target url supplied. 

Jing

**Comment by mreyescdl** [comment]
Hi Jing,

I believe the 2 GETs are for a different ALB (Storage and Inventory), not EZIDs.

Looking at the 2 PUTs that do hit EZID, are you able to see the 401 response in your application logging?

**Comment by jsjiang** [comment]
Hi Mark,
For each PUT, we see two log entries in the Apache log. For the successful ones they are in the "401" and "201" sequence. For failed ones, they are "401' and "400". Please see sample log entries in [a previous comment (https://github.com/CDLUC3/ezid/issues/161#issuecomment-1641014717). 
I don't know why a 401 is logged for each PUT. I can take a look into the code.

Jing

**Comment by jsjiang** [comment]
Regarding the "401" errors:
I found the following statement from the EZID API doc:

"The downside of using higher-level authentication mechanisms is that they often do not supply credentials initially, but only in response to a challenge from EZID, thus doubling the number of HTTP transactions."

I think the "401"s are the responses to the initial requests without credentials.

**Comment by jsjiang** [comment]
@mreyescdl Hi Mark,
Can you share Merritt code on:
1. The operations on the initial metadata without the target url field,
2. The operations on the metadata with the target url field.

I suspect the issue is workflow related. The EZID minting operation with POST on https://ezid.cdlib.org/shoulder/<prefix> performs two things:
1. mint an identifier - a new ark or doi string created from the minter
2. register the identifier with provided metadata - this calls the createIdentifier function

Once the minting operation has completed, we suppose to use POST but not PUT on https://ezid.cdlib.org/id/<ark or doi> to update the metadata. If you really preferred to use PUT in this case, you can add an option "update_if_exists=yes".

Jing

**Comment by mreyescdl** [comment]
@jsjiang We were able to find the 502 that Ingest received in the ALB logs.  It is shown below.
The ALB forwarded the POST request to host `uc3-ezidui02x2-prd.cdlib.org` at `2023-07-18T09:11:20` UTC (2AM Local)
Do you see any evidence in this on the host logs?  Thanks

```
https 2023-07-18T09:11:20.260546Z app/uc3-ezidui-prd-alb/245ca6c65f652711 54.244.52.27:46796 172.30.18.6:80 0.001 0.001 -1 502 - 455 277 "POST https://ezid.cdlib.org:443/id/ark:/13030/m5fc4q9f HTTP/1.1" "Apache-HttpClient/4.5.13 (Java/1.8.0_372)" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:451826914157:targetgroup/uc3-ezidui-prd-tg/aca7f4629cba0644 "Root=1-64b65738-449335b3233641c244b90429" "ezid.cdlib.org" "arn:aws:acm:us-west-2:451826914157:certificate/331bf148-32eb-4a36-aa93-14c8b807e5f6" 0 2023-07-18T09:11:20.259000Z "waf,forward" "-" "-" "172.30.18.6:80" "-" "-" "-"
```

**Comment by jsjiang** [comment]
@mreyescdl Hi Mark,
There are two 'createIdentifier' actions for 'ark:/13030/m5fc4q9f' on 7/18 at 2:11:19am and 2:11:20am. The 2nd one failed as EZID does not allow creating identifier on an existing ID unless you supply the "update_if_exists=yes" option.  

I think the 2nd 'createIdentifier' action was trying to update the record with additional data field: '_target=http://merritt-aws.cdlib.org/m/ark%253A%252F13030%252Fm5fc4q9f'. Anyway you can add "update_if_exists=yes" option to the request?

```
2023-07-18 02:11:19,803     INFO 0ee9b466254b11ee9fd206a406a5cd13 BEGIN createIdentifier normalizedIdentifier="ark:/13030/m5fc4q9f" user.username="merritt" user.pid="ark:/99166/p9td9n725" user.group.groupname="merritt" user.group.pid="ark:/99166/p9pn8xd8d" metadata="erc=who:%20UC/JEPS%20Herbaria%0Awhat:%20Schizaea%20elegans%20(Vahl)%20Sw.%20/%20Pteridophytes%20/%20%20/%20%20/%20F%20(Project%20Code)%0Awhere:%20UC1978323.TIF,mrt.creator=ucjeps_img_archive"
2023-07-18 02:11:20,304     INFO 0f362b98254b11ee9fd206a406a5cd13 BEGIN createIdentifier normalizedIdentifier="ark:/13030/m5fc4q9f" user.username="merritt" user.pid="ark:/99166/p9td9n725" user.group.groupname="merritt" user.group.pid="ark:/99166/p9pn8xd8d" metadata="erc=who:%20UC/JEPS%20Herbaria%0Awhat:%20Schizaea%20elegans%20(Vahl)%20Sw.%20/%20Pteridophytes%20/%20%20/%20%20/%20F%20(Project%20Code)%0Awhere:%20ark:/13030/m5fc4q9f%0Awhere:%20UC1978323.TIF,mrt.creator=ucjeps_img_archive,_target=http://merritt-aws.cdlib.org/m/ark%253A%252F13030%252Fm5fc4q9f"
```

Jing

**Comment by jsjiang** [comment]
@mreyescdl @ashleygould
Additional info:
1. The above entries are from the EZID application log.
2. The POST request Mark provided on 7/18, 2am local time for `ark:/13030/m5fc4q9f` with `Root=1-64b65738-449335b3233641c244b90429`: it only shows in WAF log but not in ALB or EZID app. [See OpenSearch log entries here](https://search-os-uc3-logging-stg-suwz42vownvyte6ivqazeifz44.us-west-2.es.amazonaws.com/_dashboards/goto/5349c85e6b7f51ce851bf7da3ba1db51?security_tenant=global)
3. I think this is the regular minting workflow from Merritt (Mark, correct me if I am wrong):
1) Issue a POST request on shoulder "POST /shoulder/ark:/13030/m5" to mint an identifier and to attach the initial metadata to the identifier
2) Issue a POST request on the newly minted identifier to update the metadata, such as "POST /id/ark:/13030/m59m3znm"

Somehow, the requests ended with 502 errors used "PUT" in step 2 instead.

Jing

**Comment by mreyescdl** [comment]
@jsjiang Actually, I believe the initial POST request is swallowed up by the ALB and the application never sees it.  I noticed a similar issue with another Merritt ALB.

Our workflow first tries to mint an ID with a POST and if this fails (such as a 502 error) it assumes that it is already created and issues an update with a PUT.  This too will fail in this case since it was never created (due to the 502).  We may retry the request which is why you see 2 PUTs.

I do not use the update PUT with "update_if_exists=yes", but I'll look into this.
Question: What is the better way to update an ID? POST or PUT?  The API docs mention both can be used to update.

For the 502 errors, I'm continuing to research.  I'm trying to see if it a target host issue or ALB issue.

**Comment by jsjiang** [comment]
@mreyescdl Hi Mark,
**PUT** only works in two situations:
1. When you want to [create an identifier](https://ezid.cdlib.org/doc/apidoc.html#operation-create-identifier). This means you define an identifier, for example 'ark:/99999/fk4test_1234' and provide that ID to EZID through: `PUT <ezid-host>/id/ark:/99999/fk4test_1234`. To be successful, ID 'ark:/99999/fk4test_1234' should not already exist in EZID. Otherwise you will receive an error.
2. When you are not sure if an identifier already exists in EZID, you can use the PUT with the "update_if_exists=yes" option. This is so called [create or update operation](https://ezid.cdlib.org/doc/apidoc.html#operation-create-or-update-identifier). EZID will create an identifier if it is new otherwise it will update the record.

To answer your question on "the better way to update an ID":
* Use POST when you are confident that the ID exists;
* Otherwise, use PUT with the "update_if_exists=yes" option

Back to your workflow:

If the minting an ID with a POST fails without a minted ID, then I would suggest to retry the minting operation. If the minting operation fails with an ID returned, then you may want to try use PUT with "update_if_exists=yes" option.

Jing

**Comment by mreyescdl** [comment]
Hi @jsjiang 

Thanks.  I'll look into modifying our client code to use the "update_if_exists" query parameter.

I've look a bit more at the 502 issue and have a couple of observations.
You mention your EZID stack is ALB-->Apache-->Django
The ALB had a default idle timeout of 60 seconds.  However, it looks like your Apache server has the default value of 15 seconds for "Keep Alive". I believe if a request takes longer than this then Apache will drop the connection from the ALB.  Is it possible that under load EZID would exceed 15 seconds to service a request?

Also, I noticed a lot of application timeouts in your host journal file.  These may be unrelated, but thought I'd pass it along.
```
Jul 28 04:01:06 uc3-ezidui02x2-prd ezid-proc-errorlog[9105]: urllib.error.URLError: <urlopen error timed out>
Jul 28 04:01:07 uc3-ezidui02x2-prd ezid-proc-errorlog[9105]: ERROR ezidapp.management.commands.proc-link-checker 140541656295168: HTTPError
```

**Comment by mreyescdl** [comment]
Digging into the EZID stack a bit further, there really is not a reverse proxy in Apache.  Instead, Apache is launching the Django process in a specified configuration and forwarding requests to the daemon process.
There are timeout settings that can be used during initialization.  "inactivity-timeout" and "request-timeout" stand out as relevant.  However, the docs do not specify what the default value is, so it is unclear if this would help.

```
https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html
```

**Comment by jsjiang** [comment]
@mreyescdl Thank you Mark for looking into Apache configurations. 
The 502 errors are showing up in the ELB log on OpenSearch now. These requests probably never made to EZID due to timeout. I also noticed that trafic on EZID was heavy when 502 errors occurred. I will look into timeout setting and also work on tightening the WAF rules.

**Comment by jsjiang** [comment]
Note: ELB log showed 9 bad gateway errors (502) on 7/27, 28, 29 for POST requests from Merritt https://ezid.cdlib.org:443/shoulder/ark:/13030/m5. This is a minting request which requires access to the Berkeley DB hosted on the EZID server.

**Comment by rushirajnenuji** [comment]
related #450

**Comment by mreyescdl** [comment]
Hi Jing,

Analyzing a series of 502s occurring at "2023-07-27T20:28:10.950550Z" shows that these 502 coincide with a spike in Network I/O from the Librato graph (linked below.)  This may show that the 502s are resource related.  In the series of 502s (e.g. shown below) the "response_processing_time" is set at -1 which may mean that the ALB did not receive a response from the host.

I think looking at the host as you mentioned and at the timeout settings is a good approach.
Please let me know if you would like to discuss this in a zoom session.

https://metrics.librato.com/s/public/5t9drxwai?duration=172800&end_time=1690578000&source=%2Aezid%2A02%2Aprd%2A


```
451826914157_elasticloadbalancing_us-west-2_app.uc3-ezidui-prd-alb.245ca6c65f652711_20230727T2030Z_52.37.210.86_1quuzegi.log:https 2023-07-27T20:28:10.950890Z app/uc3-ezidui-prd-alb/245ca6c65f652711 35.173.47.68:57782 172.30.18.6:80 0.002 0.057 -1 502 - 146 272 "GET https://ezid.cdlib.org:443/id/ark:/81985/n2xp6z05x HTTP/1.1" "nulib-ark-checker/0.1.0" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-west-2:451826914157:targetgroup/uc3-ezidui-prd-tg/aca7f4629cba0644 "Root=1-64c2d35a-10c5a1787925f9b375ed7988" "ezid.cdlib.org" "arn:aws:acm:us-west-2:451826914157:certificate/331bf148-32eb-4a36-aa93-14c8b807e5f6" 0 2023-07-27T20:28:10.892000Z "waf,forward" "-" "-" "172.30.18.6:80" "-" "-" "-"
```

**Comment by jsjiang** [comment]
Outcomes from Mark, Ashley and Jing's meeting on 8/3:
Action items:
1. Write custom WAL rules to reduce malicious requests - Jing with Ashley's support
2. Replicate 502 error in the EZID stage environment - Mark & Jing (targeting the minting operation that requires read/write access to both the Berkeley DB and MySQL) 
3. Refactoring Merritt 502 error handling - Mark (re-try minting operation when receiving 502 error)
4. Migrate berkeley DB to MySQL - Jing
5. Develop a testing/evaluating process before proceeding to the following options - Jing with Ashley's support
6. Adjust Apache/mod_wsgi rate limiting
7. Adjust mod_wsgi keep-alive and ALB timeout settings
8. Increase Apache concurrent requests limit
9. Upgrade EC2 instance

**Comment by mariagould** [comment]
Merritt sorted for now and we will address other performance issues via other tickets.
