### ISSUE TITLE
Migrate from Travis CI to Github Actions

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#165]
Travis CI has made significant changes to their platform which prompts us to move to Github Actions for our continuous integration testing workflow.  

Here are some references in this area as well as Dryad pull requests which outline their migration from Travis to GA.  
Review

- https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions
- https://github.com/CDL-Dryad/dryad-app/pull/317

- [x]  Marisa will schedule a meeting with UC3 developers to discuss and address and questions (not needed)

**Comment by rushirajnenuji** [comment]
Roger confirmed on today's call that this is completed
