### ISSUE TITLE
Stage EC2 Instance type size increase; Stage RDS instance and storage type increase

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#174]
Footprints ticket 14440: changed EC2 instance type for host uc3-ezidui02x2-stg from t3.small to c5.xlarge
(during a joint meeting): changed RDS instance type for rds-ias-ezid-search1-py3-stg from db.t3.small to db.m5.xlarge
(during a joint meeting): changed storage type for rds-ias-ezid-search1-py3-stg from general to provisioned IOPS=3000

After testing and production release, we'll need to roll back these instance types for cost savings.

**Comment by ashleygould** [comment]
all rds and ec2 instances have been resized back to pre-migration instance types.
