### ISSUE TITLE
Attempt to delete an identifier on stage3 raises a 500 error

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#202]
Attempting to delete a previously created identifier raises a 500 error on stage3. This action works on stage2.

```
$ tools/client.py "${SERVER}" "${SESSION}"  c "ark:/99999/fk4m8n11n" target http://test.net
success: ark:/99999/fk4m8n11n

$ tools/client.py "${SERVER}" "${SESSION}"  d "ark:/99999/fk4m8n11n"  2>&1 | more
500 HTTP Error 500: Internal Server Error
```

**Comment by datadavev** [comment]
Exception being raised is (from the html response):
```
Exception Type:
TypeError

Exception Value:
enqueue() takes 2 positional arguments but 3 were given

Exception Location:
/ezid/ezid/impl/ezid.py, line 506, in deleteIdentifier
```

**Comment by datadavev** [comment]
Roger reports that it is working on his local system, maybe.

**Comment by rogerdahl** [comment]
Still working for me. Let's test after new deploy to stg-py3.

**Comment by rushirajnenuji** [comment]
- status: SUCCESS (ezid-py3-stg on 03/02/2022)
- tried to delete identifier `doi:10.5062/F4HH6H9F` as admin
  - result: successfully deleted the identifier
