### ISSUE TITLE
Identifiers do not show up in "Manage IDs"

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#212]
Newly created identifiers should show up in a user's "Manage IDs" page in the EZID UI. This does not appear to be the case for our py3 version. 

To reproduce:
1. Log in as user.
2. Create a new identifier
3. Check to see if new identifier is listed in user's "Manage IDs" page

I tested this on stage and newly created identifiers show up instantaneously. 

Screenshots show newly created identifier and then no evidence of identifier in "Manage IDs"

![Screen Shot 2022-02-02 at 11 45 31 AM](https://user-images.githubusercontent.com/45110557/152226266-7bf64895-0169-4ab3-af64-2cb81ccfead2.png)

![Screen Shot 2022-02-02 at 11 48 42 AM](https://user-images.githubusercontent.com/45110557/152226221-f8f2ee9d-05a7-429a-a839-602b37967c5b.png)

**Comment by mariagould** [comment]
Tested this successfully on py3

**Comment by rushirajnenuji** [comment]
- status: SUCCESS (ezid-py3-stg on 03/02/2022)
- created a new user
  - created a new identifier
    - visited the identifiers page, the process took few seconds (3-5s), the newly created identifier showed up in the manage ids section for that user
