### ISSUE TITLE
New user creation does not populate the group that the user is assigned to.

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#230]
The user account is functional, but is not showing up in the group.

Reported by @mariagould

**Comment by mariagould** [comment]
@datadavev @rogerdahl  I am no longer able to reproduce this. 

@rushirajnenuji are you able to reproduce? If not, we should consider this resolved.

**Comment by rushirajnenuji** [comment]
- status: FAILURE (ezid-py3-stg on 03/02/2022)
- created a new user `py3febu2` for group `ezidpy3testgroup`
  - the user can inherit all group properties, and can successfully use group shoulders
  - the user however does not show up in the group profile page

**Comment by mariagould** [comment]
Tested this again today and I was not able to get a new user to show up in a group. 

Steps to reproduce: 
- Create new group (ezidtestgroup3)
- Create new user (ezidtestuser4) and assign to above group while creating the account (a group assignment is required at account creation
- Check the list of users associated with the group in the group profile

Screenshots show that the group is associated with the user, but the user does not appear in the group's list of users. 
![Screen Shot 2022-03-24 at 4 06 27 PM](https://user-images.githubusercontent.com/45110557/160024548-1bf353da-bd07-418d-96a0-f7ffc3cd9a45.png)
![Screen Shot 2022-03-24 at 4 06 36 PM](https://user-images.githubusercontent.com/45110557/160024550-31b08e96-aaae-4a76-884d-35edec23fd9f.png)

**Comment by datadavev** [comment]
Seems likely to be a rendering issue

**Comment by datadavev** [comment]
The inline userlist for the group is generated in https://github.com/CDLUC3/ezid/blob/e89a590634c69ef5665d36b1edd0fd6fbe2114ba/ezidapp/admin.py#L556

**Comment by mariagould** [comment]
Tested again and this is working as expected. 

Operations tested:
- Create new user `ezidgrouptest` and add to existing group `ezidtestgroup3`
- Create new group `ezidgrouptest` add new user `ezidgrouptest2` to group
