### ISSUE TITLE
Some proxy assignments return errors

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#232]
Designating a proxy user fails in certain cases and it is not clear what causes the assignment to fail. The error message appears to be disconnected from the expected error. 

This has been reproduced on both stage py2 and stage py3. The error handling is different in each case. The proxy assignment in stage py2 throws an error but the proxy assignment is still successful. However, in stage py3 the assignment is not successful. 

It seems as though the error is associated with specific users. For example:

**Stage Py2:**
Example of proxy assignment that is successful without returning error:
- Task: Make user `cdldmptool` a proxy of user `proxytesting`
- Result: Successful proxy assignment without error message

Example of proxy assignment that is successful but returns error:
- Task: Make user `proxytesting` a proxy of user `dash`
- Result: Receive error banner message in admin screen ("Error updating user PID") (see screenshot) but proxy assignment is successful

![Screen Shot 2022-02-28 at 5 11 20 PM](https://user-images.githubusercontent.com/45110557/156085755-b2069fde-8124-4977-aed7-c81f37d700ec.png)

**Stage Py3:**
Example of proxy assignment that is successful without returning error:
- Task: Make user `dmptool` a proxy of user `proxytesting`
- Result: Successful proxy assignment without error message

Example of proxy assignment that is not successful and returns an unclear error:
- Task: Make user `proxytesting` a proxy of user `dmptool`
- Result: Proxy assignment fails with yellow error screen (see screenshot)

![Screen Shot 2022-02-28 at 5 07 06 PM](https://user-images.githubusercontent.com/45110557/156085827-e40198b0-a491-4d61-805f-f0abe3832c5f.png)

It is not clear (a) which conditions cause the proxy assignment to fail, and (b) why the error handling is different in py2 vs py3

**Comment by rogerdahl** [comment]
This fixes the issue in the screenshot, but may not fix any issue that has carried over from the Py2 version.

**Comment by mariagould** [comment]
Tested this again and I am still getting the screenshot error. Is this expected?

I did the following:
For user `deletethisuser`, add proxy `dmptool`
For user `deletethisuser`, add proxy `ezidtestuser4`

Both operations returned the yellow screen error as reported previously.
