### ISSUE TITLE
Delete user with management operations with delete identifier flag results in some identifiers not being deleted.

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#233]
This appears to be an issue with cascading delete operations

**Comment by datadavev** [comment]
Action is to update the command to check that the user does not have identifiers associated with before proceeding.

Removing the identifiers is a step that should be performed beforehand.

**Comment by rogerdahl** [comment]
To test, attempt to delete a user that has identifiers. E.g.,

```shell
$ ./manage.py user-delete apitest
```
Should return:
```
CommandError: Cannot delete user: User is the owner of one or more identifiers
```

**Comment by rushirajnenuji** [comment]
This is fixed, in order to delete the user, we need to delete the identifiers for that user (separate script) and then proceed with deleting the user. Both the scripts are available in the tools directory.
