### ISSUE TITLE
Adjust logging for verifying new code actions

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#25]
(Update this issue with specific actions for improving logging)

Need to improve logging messages and the coverage of logging.

- [x] Consistent time stamps for log messages
- [x] Separate logs for detail vs operational
- [x] Increase coverage of logging statements to help diagnose issues as they emerge
- [x] Ensure that messages resulting in an email are easily found
- [x] Support logging from multiple threads
-  Ensure that management operations are logged

**Comment by datadavev** [comment]
Collecting some notes on logging best practices here: https://hackmd.io/VTkPqgc7Q6eAhcGUNG-org

**Comment by mariagould** [comment]
@datadavev will create a separate issue about capturing management operations in logs
