### ISSUE TITLE
Update Django model index_together fields before creating initial DB migration for EZID

### ISSUE THREAD

**Issue by rogerdahl** [CDLUC3/ezid#289]
Update the model classes under `ezidapp/models` to include the multi-field indexes that we created during the custom DB migration and any indexes added to the DB manually.

To get Django to automatically generate multi-field indexes, add a Meta subclass and an index_together attr that holds a list of tuples:

```python
    class Meta:
        index_together = [
            ("owner", "identifier"),
            ("ownergroup", "identifier"),
            ...
        ]
```

**Comment by datadavev** [comment]
Actions:
- [ ] Collate the indexes that were manually run
- [ ] Update the Meta subclass
