### ISSUE TITLE
Crossref DOI metadata includes "WITHDRAWN" in titles

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#297]
The CDL publishing team reported that their Crossref DOIs are showing up with the word "WITHDRAWN" added to the beginning of the title metadata. The metadata looks fine in EZID, but the Crossref deposit shows the metadata with the added word. This is happening for DOIs registered via their preprint platform as well as their journal publishing platform, and seems to have been happening only since the Python3 upgrade, so it seems to be something awry on our end.

Example DOIs
doi:10.5070/P538257522
doi:10.31223/X5KH17

**Comment by datadavev** [comment]
Original implementation:  https://github.com/CDLUC3/ezid/blob/04e89b4b33aae7308f95007524aff4d7d693a63c/impl/crossref.py#L482

Current implementation: https://github.com/CDLUC3/ezid/blob/17d0a7f3228073fd558c594a3b30eb27f6ea6cf6/ezidapp/management/commands/proc-crossref.py#L119

Probably should be `ref_id.isUnavailable`

**Comment by mariagould** [comment]
List of affected DOIs: https://gist.github.com/rushirajnenuji/3883891bd54ef81ae2be1c961a1d3c33
