### ISSUE TITLE
DataCite DOI registrations via API are incorrectly handling publication year

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#312]
UCLA reported a couple of DataCite DOIs with a publication date of 2022 that had the date converted to 0000 in DataCite metadata. The metadata looks fine in EZID:

- doi:10.17610/t6zg6v (https://commons.datacite.org/doi.org/10.17610/t6zg6v)
- doi:10.17610/t6bs4m (https://commons.datacite.org/doi.org/10.17610/t6bs4m)

If you follow the DataCite Commons links and open the metadata in XML or JSON you can see the date converted to 0000.

Upon further investigation, other DOIs with the same issue were identified. Some examples:

- doi:10.7922/G21G0JKP
- doi:10.6078/M7959FPN

Following further investigation, we are hypothesizing that this issue has been happening since the Python3 upgrade and is isolated to DataCite DOI registrations made via the API. DataCite DOI registrations made via XML do not appear to be affected. The issue seems to have something to do with how we are validating the publication year. The validation logic is supposed to set 0000 if no valid date is provided, but this is happening even when a valid date is provided. 

Example DOIs that were registered after the upgrade but are not affected:

- doi:10.25346/S6/CXO9PD
- doi:10.21973/N38D5T
- doi:10.25345/C5WD3Q54Q

**Comment by datadavev** [comment]
Possibly related to #311

**Comment by datadavev** [comment]
Issue is that the `validatedDate` property of metadata is not being set when setting metadata via api using ANVL properties. This should be set in the method `mapping.map()` on around line 258 as is done for `km._validatedType`

**Comment by datadavev** [comment]
Actually, on further evaluation the issue is in `validation.publicationDate()`. The `km` variable is an instance of `KernelMetadata` which provides a getter for `validatedDate`, which in turn calls `validation.publicationDate()`. That method has an error in generating the validated date string after parsing to a date.
