### ISSUE TITLE
MySQL 5.7 to 8.0 upgrade by Dec 2022

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#325]
IAS is working to upgrade all RDS instances from MySQL 5.7 to 8.0 by the end of 2022.

EZID team should plan to work with IAS to upgrade dev/stg environments and test before moving to production.

https://severalnines.com/blog/moving-mysql-57-mysql-80-what-you-should-know/

**Planned schedule:**

- [x] Dev upgrade: October 13
- [x] Testing on dev: October 13-27
- [x] Stage upgrade: October 27
- [x] Testing on stage: October 27-November 10
- [x] Prod upgrade: November 10

**Comment by marisastrong** [comment]
More information on this here: https://confluence.ucop.edu/display/CUG/RDS+User+Guide#RDSUserGuide-MySQL5.7to8.0Upgrade

**Comment by datadavev** [comment]
The AWS upgrade process runs a pre-check to verify compatibility. If the pre-check fails, then no action is taken and a log is generated for review.

Seems the simplest process is to initiate upgrade of the dev RDS instance. If that runs, then test the app and if all ok, continue with stage then production upgrades. The dev and stage upgrades will provide a good indication of the expected downtime.

A cursory review of the changes from 5.7 to 8.0 suggest that the there should not be any incompatibilities. This will be confirmed with the upgrade pre-check.

**Comment by marisastrong** [comment]
Thanks for this Dave.  I'll check with IAS on the pre-check.  I hadn't heard of this step and it seems like a logical first step for the migration.


________________________________

**Comment by marisastrong** [comment]
[EZID-PrePatchCompatibility.log](https://github.com/CDLUC3/ezid/files/9780570/EZID-PrePatchCompatibility.log)

3) Usage of utf8mb3 charset
    The following objects use the utf8mb3 character set. It is recommended to convert them to use utf8mb4 instead, for improved Unicode support.
    More Information:
        https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html

**Comment by marisastrong** [comment]
- [ ] Bring down service and background jobs
- [ ] Maintenance page will be displayed
- [ ] IAS will perform MySQL upgrade
- [ ]

**Comment by ashleygould** [comment]
prod upgrade completed Nov 17
