### ISSUE TITLE
Add query max execution time configuration property

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#357]
MySQL supports a [`max_execution_time`](https://dev.mysql.com/blog-archive/server-side-select-statement-timeouts/) property to limit the time that an individual query can run. This may be helpful to prevent  blocking access to the mysql database. An example config looks like:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'example_db',
        'USER': 'example_user',
        'PASSWORD': 'example_password',
        'HOST': '127.0.0.1',
        'OPTIONS': {
            'init_command': 'SET max_execution_time=1000'  # In milliseconds
        }
    }
}
```

Note that since background jobs are sharing the same config, this property should be set with those operational requirements in mind, unless an alternative config is used for background vs web apps.

**Comment by sfisher** [comment]
The may be related to searching and I believe OpenSearch resolves most of the problems with log-running search queries, though there may be other queries that could be long running.

**Comment by datadavev** [comment]
Yep, this can be closed since there's no user facing interaction queries that are timing out with use of OpenSearch.
