### ISSUE TITLE
Completed tasks are not being purged from queues

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#371]
Tasks that are successfully completed or are a "no op" for a particular queue should be removed.

Tasks that result in an error condition should be presented to an operator to determine the course of action, and tooling should be available to enable such action to be taken.

- [ ] Add some documentation describing task progression through the queues
- [ ] Add a management command that removes completed / noop tasks from the queues
- [ ] Enable inspection and administrative actions for tasks that caused an error condition

**Comment by mariagould** [comment]
duplicates #394
