### ISSUE TITLE
lots of Service Unavailable errors

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#374]
Starting about 13:21 ET EZID production started emitting Service Unavailable errors. All were from requests of the form:

```
Service Unavailable: /id/ark:/62930/XXXX
```
Where `XXXX` is an ark value.

This appears to be a case of load exceeding the system capability to respond. The available logging information was not sufficient to fully diagnose the problem.

Immediate actions:

- [ ] Update the EZID apache httpd config to log the external client IP. 
- [ ] See if we can get ELB logging exposed
- [ ] Review ELB configuration and perhaps align throttling to better match the Django app capabilities

**Comment by datadavev** [comment]
Apache httpd config is `/apps/ezid/etc/httpd/conf.d/03-ezid-nossl.conf`, therein:

```
	ErrorLog /ezid/var/log/httpd/ezid_error.log
	LogLevel warn
        CustomLog /ezid/var/log/httpd/ezid_access.log combined
```
 with the `combined` format defined in `/apps/ezid/etc/httpd/conf/httpd.conf`:
```
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
```

**Comment by datadavev** [comment]
As documented for [AWS ELB](https://aws.amazon.com/premiumsupport/knowledge-center/elb-capture-client-ip-addresses/), the log format should be adjusted to include `X-Forwarded-For` which will be the client ip accessing the service.

**Comment by datadavev** [comment]
Using locust to evaluate effects of load on stage. A task definition of calling `/id/` with a pseudo-random set of identifiers, with requests from a user 0.01 seconds apart was used. Failures started to appear at 28 users with a total request rate of about 75/sec. The max response rate was about 76/sec at 27 users. Once errors started to appear, the response rate dropped significantly to about 60/sec, apparently due to error handling overhead - there were also a lot of requests to error page assets, probably triggered by email servers retrieving the content, further exacerbating the load on the server.

![total_requests_per_second_1674749404](https://user-images.githubusercontent.com/605409/214895045-e4ea37fb-f12c-408a-b85f-760b698217ba.png)

**Comment by jsjiang** [comment]
2nd discussion item with IAS: recommendation on setting up the rate limit value.

**Comment by marisastrong** [comment]
The rate limit would be applied via WAF, not the ELB.  However WAF blocks malicious traffic so might not be the best approach.  IAS will reach out to AWS rep to determine a solution that makes sense.  50 requests/second is what would be idea based on the load testing above.

**Comment by mariagould** [comment]
Closing this and creating a separate issue for the WAF aspect of this work.
