### ISSUE TITLE
error: bad request - character decoding error

### ISSUE THREAD

**Issue by tedhabermann** [CDLUC3/ezid#375]
I am getting this error from a number of xml files (like the attached) I am trying to insert into EZID... Any pointers on tracking these down?
[10.82164_100501.47613.txt](https://github.com/CDLUC3/ezid/files/10514324/10.82164_100501.47613.txt)

Thanks very much for the help,
Ted Habermann

**Comment by mariagould** [comment]
Hi Ted - can you share the error message you're getting?

**Comment by tedhabermann** [comment]
Maria - thanks for getting back... It is a little complicated...

I have 85 xml files to make into EZID identifiers. The file attached here (100501.31635) worked in ezidclient.py and created this identifier: success: doi:10.17913/F3H59Q | ark:/c7913/f3h59q. I have not figure out how to control the DOI using that client, so I wrote one myself... 

That client is what is creating this error message - the one in the issue title: error: bad request - character decoding error. 26 out of 85 files are having this problem... I can send more if that is helpful...

I hope that clarifies the problem, but I'm not sure...

Ted

[10.82164_100501.31635.txt](https://github.com/CDLUC3/ezid/files/10514870/10.82164_100501.31635.txt)

**Comment by mariagould** [comment]
Thanks, Ted. What do you mean by "control the DOI"?

**Comment by tedhabermann** [comment]
I would like to specify the suffix. If these were completely new DOIs, I would go opaque, but I am migrating works from the UCNRS RAMS system and would like to use suffixes that make sense to the creators and managers of that system.

**Comment by tedhabermann** [comment]
The root of the problem in this case was the Content Type in the request header. Has to be 
headers =  {'Content-Type':'text/plain; charset=UTF-8'} to send utf-8 content in the post...
Obvious in retrospect...
