### ISSUE TITLE
Change log level in production from DEBUG to INFO

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#376]
The log level in EZID production has been set at DEBUG level since the python 3 deployment. This was deliberate to facilitate tracking issues related to that release, however there is a performance penalty that can be troublesome at high loads.

The logging config is managed in `settings.py.j2`, currently starting line 213 `logging.config.ConfigDict`. The value of `level` for each of the handlers should be set to `INFO`, and the root logger, i.e. the `logger` entry with a blank name should also be set to `INFO`.

**Comment by marisastrong** [comment]
Awaiting Jing to learn the deployment process before this is  pushed out to production

**Comment by datadavev** [comment]
Ideally this should be set by a jinja template variable with settings applicable to each environment. This would enable different log levels for each environment.

**Comment by jsjiang** [comment]
Ashley created SSM parameter "log_level" and set default value to "INFO" and stage value to "DEBUG"

ssm-param-get /uc3/ezid/ui/default/log_level
INFO

ssm-param-get /uc3/ezid/ui/stg/log_level
DEBUG
