### ISSUE TITLE
Bug: DataCite DOIs with resource type "conference paper" fail validation

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#383]
This was originally reported by an EZID user at UC Santa Cruz:

**Summary of the problem**
DataCite DOIs with the resource type "conference paper" are not passing validation when the DOI is registered or updated in the EZID UI. This was replicated across the various ways in which a DOI can be manipulated in the UI:
- Registration via the homepage demo
- Registration via "Simple Create"
- Registration via "Advanced Create"
- "Make changes" function on identifier landing page

When DOI is created as "Reserved" with the conference paper resource type, the validation error does not occur (presumably because the validation test is not executed at that point). However, if the reserved DOI is then made public, the validation error does occur. 

**Analysis**
Based on my investigation, my theory is that this is caused by an issue with the metadata generation for this particular resource type: the resource type "Conference Paper" (as it appears in the UI) should appear in the generated metadata as "ConferencePaper" according to DataCite conventions. A test via the API appears to bear this out:

- DOI registration with type "ConferencePaper" is successful
- DOI registration with type "Conference Paper" is unsuccessful

**Steps to reproduce:**
- From homepage demo, register DOI with resource type "Conference Paper"
- As logged-in user, register DataCite DOI with resource type "Conference Paper" (Simple and Advanced Create mode)
- As logged-in user, register reserved DOI with resource type "Conference Paper"
- As logged-in user, make reserved DOI public with resource type "Conference Paper"

Attaching some screenshots of the errors for reference. 

**My recommended resolution:**
- Fix metadata generation rule for UI registrations to change "Conference Paper" to "ConferencePaper"
- For good measure, check all other resource types to make sure formatting is correct
<img width="909" alt="Screenshot 2023-02-27 at 10 48 49 AM" src="https://user-images.githubusercontent.com/45110557/221662379-04a1fa20-c598-49d0-93ee-5d9079c1fc0b.png">

<img width="814" alt="Screenshot 2023-02-27 at 11 23 37 AM" src="https://user-images.githubusercontent.com/45110557/221662461-bcfa5b40-e374-48d3-8f0a-74fc2b257fe1.png">

<img width="952" alt="Screenshot 2023-02-27 at 11 26 40 AM" src="https://user-images.githubusercontent.com/45110557/221663224-52e23357-af89-46fa-8738-55110fc46a1f.png">

**Comment by datadavev** [comment]
In `impl/form_objects.py`:
[`('Conference Paper', _('Conference Paper')),`](https://github.com/CDLUC3/ezid/blob/18a9f4e3abcc26683e0449d0af0472bd7e0cd6d3/impl/form_objects.py#L50) 
should be 
`('ConferencePaper', _('Conference Paper')),`

**Comment by rushirajnenuji** [comment]
@jsjiang  released and deployed a new version to fix this https://github.com/CDLUC3/ezid/releases/tag/3.0.16
