### ISSUE TITLE
Download request will never be formatted

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#386]
https://github.com/CDLUC3/ezid/blob/2d1c35048ca66fe42eaaffa9d7ec3c10e6dc5028/ezidapp/management/commands/proc-download.py#L453

This format string will never get formatted. It needs to be switched to either f-string formatting, named-values with the `format()` method, or the `%` operation. Suggest using f-strings for consistency. e.g.:

```python
msg = (
  f"{salutation}Thank you"
  "..."
  f"{django.conf.settings.EZID_BASE_URL}/download/..."
  "..."
)
```
except of course replacing all the %s entries with the corresponding named values.

**Comment by jsjiang** [comment]
Fix is on ezid-stg (3.0.17rc0) ready for testing.
