### ISSUE TITLE
`django.utils.translation.ugettext` is deprecated

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#388]
Django docs[^1] indicate the `ugettext()` method is deprecated and can be replaced with `gettext()` with no side effects.

This change should not have any functional impact, but will help ensure a smooth upgrade to future versions of Django.

This method is used in many of `impl/ui_*` for loading region specific text.

[^1]: https://docs.djangoproject.com/en/dev/releases/3.0/#features-deprecated-in-3-0

**Comment by jsjiang** [comment]
Resolved by upgrading Django to 4.2.11 #583
