### ISSUE TITLE
DataCite DOIs not resolving

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#390]
A user at UCI is registering DataCite DOIs using the dc profile and the DOIs are not resolving. I want to think that the dc profile is what is causing the issue but they claim they have used this in the past without any issues, so I'm not sure exactly what is going on.

Example DOI: https://doi.org/10.24432/C58P6J

User: uci-cs

Details from user:
Recently, we created DOIs for approximately 500 datasets using the EZID account affiliated with the UCI Department of Computer Science and the EZID python command line tool. Despite all DOIs being present on our dashboard, the DOI links do not redirect to the corresponding dataset webpages, instead leading to an error page stating that the DOI cannot be found.
The elements in the dc metadata set are compatible with the ones we use for datasets in our repository. We've also used dc mappings to create DOIs in the past, and we only wanted to make minimal changes to code that had already worked.
I looked up the datacite metadata profile – the elements are very similar to dc, so should also be compatible with our datasets.

**Comment by mariagould** [comment]
- [ ] Get list of DOIs
- [ ] Investigate why they are not failing validation

**Comment by jsjiang** [comment]
Cause: profile = "dc" is not passed to the function call of formRecord("doi:" + doi, m) in datacite.py/uploadMetadata. The _mapDublinCore(metadata) function is not used to map the metadata for DataCite upload.

https://github.com/CDLUC3/ezid/blob/18a9f4e3abcc26683e0449d0af0472bd7e0cd6d3/impl/datacite.py#L443

https://github.com/CDLUC3/ezid/blob/18a9f4e3abcc26683e0449d0af0472bd7e0cd6d3/impl/mapping.py#L230

**Comment by jsjiang** [comment]
Recommended fix: Modify `proc-datacite.py` to pass 'profile' through the metatdata in the `_create_or_update` function.

def _create_or_update(self, task_model: ezidapp.models.async_queue.DataciteQueue):
        ref_id: ezidapp.models.identifier.RefIdentifier = task_model.refIdentifier

        doi: str = ref_id.identifier[4:]
        metadata = ref_id.metadata
        **metadata['_p'] = str(ref_id.profile)**
        datacenter = str(ref_id.datacenter)
        r = impl.datacite.uploadMetadata(doi, {}, metadata, True, datacenter)

**Comment by jsjiang** [comment]
* Why they are not falling validation:

When profile is 'dc' or 'datacite', ezid considers these 4 input data fields: "creator", "title", "publisher", "date" required. It reports error when the required data field is missing, or when the value is empty. 

The record in question has "Unknown" value for some of the required data fields. As "Unknown"  is a non-empty string, it is valid. It is the expected behavior for the record to pass validation. 

10.24432/C58P6J
{
	"dc.date": "Unknown",
	"dc.type": "Dataset",
	"dc.title": "EBL Domain Theories",
	"dc.creator": "Unknown",
	"dc.publisher": "UCI Machine Learning Repository"
}

**Comment by jsjiang** [comment]
Code fix is on ezid-dev ready for testing. 

EZID-Dev server: http://uc3-ezidui01x2-dev.cdlib.org/

Test cases:
1. profile='erc'
2. profile='datacite', metadata is in the ANVL format
3. profile='datacite', metadata is an XML doc passed through the 'datacite' element
4. profile='dc', metadata is in the ANVL format
5. profile='crossref', metadata is an XML doc passed through the 'crossref' element

DataCite testing prefixes that work on DataCite stage:

- doi:10.5062/F4
- doi:10.21418/G8
- doi:10.6078/J8
- doi:10.6078/D1

Note: user apitest does not have access on the above prefixes, a workaround is to use the admin credentials.
 
Verifying successful sync:
- API: https://api.test.datacite.org/dois/{id}
- example: https://api.test.datacite.org/dois/10.5062/F4CR5RM5

Crossref testing
- Test prefix: doi:10.15697

Verifying successful sync:
- https://test.crossref.org/
- user credentials available in Keybase

Note: Sync with Datacite and Crossref are not enabled on ezid-dev. Manually run the sync processes before verifying on Datacite and Crossref.
