### ISSUE TITLE
Release v3.1.0 Checklist

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#399]
Release v3.1.0 checklist:
- [x] Code review
- [x] New functionality tests
- [x] Regression tests
- [x] Performance tests
- [x] Stage/Dev release for testing
- [x] operation tests
- [ ] Documentation

**Comment by jsjiang** [comment]
New functionality testing items, procedures and outputs are documented [here](https://docs.google.com/document/d/1xi36BMoD1hdq_22jhZJB2VwQxKeNVQgnkCBZrXArS84/edit#heading=h.5zyn7lwej387)

**Comment by jsjiang** [comment]
Documentation:
* EZID Identifier Resolution https://hackmd.io/@ezid/H1LAM0Tg2
* API Guide
* update ezid/doc/resolver_dev.md

**Comment by jsjiang** [comment]
@datadavev Hi Dave, can you attach performance test results to this ticket. Thank you. - Jing

**Comment by jsjiang** [comment]
Note: For the 'New functionality tests": Jing will revisit the test cases when request identifier has no matching identifiers after final implementation for matching by shoulder and NAAN .

**Comment by mariagould** [comment]
@datadavev are you still able to provide the test results? Thanks.

**Comment by datadavev** [comment]
It appears that the performance metrics I had run previously were on my laptop that had an "aquatic incident" a while back and then a failed restore from backup, so unfortunately I don't think I can add those results.
