### ISSUE TITLE
Convert hackmd version EZID Identifier Resolution doc to github

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#408]
Convert EZID Identifier Resolution - https://hackmd.io/@ezid/H1LAM0Tg2 to GitHub and save it in  ezid-ops

**Comment by rushirajnenuji** [comment]
Added to internal docs [EZID Identifier Resolution](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/resolution.md)
