### ISSUE TITLE
Investigate Service Unavailable: /shoulder/doi:10.5072/FK2 errors on 5/17 between 2:37-2:45am

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#424]
We received 186 Service Unavailable error notification emails from ezid-prd on 5/17 between 2:37am-2:45am

Email subject: [Django] ERROR (EXTERNAL IP): Service Unavailable: /shoulder/doi:10.5072/FK2

Investigate the cause and provide solutions to prevent recurring in the future.

**Comment by jsjiang** [comment]
Observations:
1. uci-cs account submitted many minting and creating IDs requests on shoulder /shoulder/doi:10.5072/FK2 during that time period - most were succeeded, some ended with  Service Unavailable errors;
2. merritt was also running metadata updates during that time period - most were succeeded, some ended with "END BADREQUEST" error; some requests ended with "Identifier.DoesNotExist: Identifier matching query does not exist" errors
3. External IP for uci-cs requests was came from IP=‘70.187.239.98'. However we only found 6 requests from this IP address in the WAF log

**Comment by jsjiang** [comment]
1. RDS metrics showed high read I/O operations (3k/sec) between 1-4am on 5/17; write I/O requests were very low;
2. RDS relatively high disk queue depth (2.2 queued I/O operations vs nearly zero in other time periods)
3. EC2 instance showed hight network I/Os around 1am before we had the "service unavailable" errors

**Comment by jsjiang** [comment]
ALB log in OpenSearch shows:
* 86 requests from this user at 2:36:57am
* 59 requests from this user at 2:41:28am
* 63 requests from this user at 2:41:29am

Based on Dave's experiments, EZID's response rate drops to about 60/sec when system is on high demands. https://github.com/CDLUC3/ezid/issues/374

**Comment by jsjiang** [comment]
EC2 instance showing memory usage pattern starting from 5/17:
* before 5/17: slightly lower than 50%
* after 5/17: jumped to around 65%
* after 5/20: jumped to around 75%

**Comment by mariagould** [comment]
Addressing via #457
