### ISSUE TITLE
Shoulder inflection fails when registration_agency_id is NULL

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#425]
The new resolver functionality includes inflection support on NAANs and shoulders, however an exception is raised when requesting metadata on a shoulder that does not have an associated registration agency (`registration_agency_id = NULL`).

For example, the NAAN 28722 lists a number of shoulders:

https://ezid.cdlib.org/ark:/28722?info
```
ark%3A/28722/h2:
    erc.who: UC Berkeley Library - HathiTrust/UCB
    erc.what: ARK
    erc.when: 2016-02-10
ark%3A/28722/k2:
    erc.who: OpenContext
    erc.what: ARK
    erc.when: 2010-02-01
ark%3A/28722/bk:
    erc.who: UC Berkeley Legacy Library bk
    erc.what: ARK
    erc.when: 2007-06-01
ark%3A/28722/d9:
    erc.who: UC Berkeley
    erc.what: ARK
    erc.when: 2011-09-20
ark%3A/28722/s7:
    erc.who: UCB Library Systems Office
    erc.what: ARK
    erc.when: 2017-02-28
ark%3A/28722/b8:
    erc.who: UC Berkeley Miscellany
    erc.what: ARK
    erc.when: 2019-02-28
ark%3A/28722/r2:
    erc.who: OpenContext identifier preregistration shoulder
    erc.what: ARK
    erc.when: 2023-05-02
```

However, requesting info on `r2` results in an error (https://ezid.cdlib.org/ark:/28722/r2?info).

Expected response is a minimal record.

**Comment by datadavev** [comment]
Further question: Should `registration_agency_id` ever be NULL? There are only 3 options: 
```
select * from ezidapp_registrationagency;
+----+---------------------+
| id | registration_agency |
+----+---------------------+
|  1 | ezid                |
|  2 | datacite            |
|  3 | crossref            |
+----+---------------------+
```

**Comment by datadavev** [comment]
This issue appears to be related to the changes made for moving minting to EZID from N2T, harking back to the implementation `shoulder-create` 50cba0339ecdefe6cfd8ef91da1982f740ae23f4

**Comment by mariagould** [comment]
@rushirajnenuji do you have any insights on this?

**Comment by datadavev** [comment]
Neither shoulder_type nor registration_agency were being set in the shoulder. This is not as bad as it seems as the information is somewhat redundant though should be set for consistency with previously created shoulders.

New shoulders created going forward will be set, but those created in the interim should be updated.
