### ISSUE TITLE
Investigate June 9 Service Unavailable errors

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#427]
We received two sets of Service Unavailable email notices on June 9:

1. The first set was received between 2:12-2:19am for requests from  uci-cs account on shoulder doi:10.24432/C5. There were 106 emails and here is a sample subject:

[Django] ERROR (EXTERNAL IP): Service Unavailable: /id/doi:10.24432/C5CP4Q

2. The 2nd set was received around 10:47am from duke on shoulder ark:/87924/r4. There were 7 emails and here is  a sample subject:

[Django] ERROR (EXTERNAL IP): Service Unavailable: /id/ark:/87924/r45b08195

**Comment by jsjiang** [comment]
uci-cs account sent us too many requests in very short time periods: 
* slot 1: 2:12:36-2:12:38 with 96 setMetadata requests, 61 succeeded,  35 failed with Service Unavailable error; 
* slot 2: 2:15:22-2:15:23 with 96 setMetadata requests, 55 succeeded, 41 failed with Service Unavailable error.

duke had similar issue. They sent us too many requests in a very short time period (over 450 requests/10 sec). 

EZID issues Service unavailable error when requests exceed a threshold (around 40/sec).

**Comment by mariagould** [comment]
Addressing via #457
