### ISSUE TITLE
Increase Apache requests limit

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#439]
Investigate how to increase Apache requests limit. Test if adjusting request limit can resolve or reduce "Service  Unavailable" error.

**Comment by jsjiang** [comment]
Can adding a Multi-Processing Module help? Possible MPM modules are:
* worker
* event
* prefork

**Comment by jsjiang** [comment]
[MaxRequestWorkers](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxrequestworkers):
For non-threaded servers (i.e., [prefork](https://httpd.apache.org/docs/2.4/mod/prefork.html)), MaxRequestWorkers translates into the maximum number of child processes that will be launched to serve requests. The default value is 256; to increase it, you must also raise [ServerLimit](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#serverlimit).

ServerLimit:
For the [prefork](https://httpd.apache.org/docs/2.4/mod/prefork.html) MPM, this directive sets the maximum configured value for [MaxRequestWorkers](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxrequestworkers) for the lifetime of the Apache httpd process.

With the [prefork](https://httpd.apache.org/docs/2.4/mod/prefork.html) MPM, use this directive only if you need to set [MaxRequestWorkers](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxrequestworkers) higher than 256 (default). Do not set the value of this directive any higher than what you might want to set [MaxRequestWorkers](https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxrequestworkers) to.

**Comment by jsjiang** [comment]
@datadavev Hi Dave, Is increasing the MaxRequestWorkers in the mpm prefork module the right approach for this?
Thank you
Jing

**Comment by mariagould** [comment]
Addressing via #457
