### ISSUE TITLE
Investigate EZID-PRD Database memory capacity issue with IAS

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#447]
We see a pattern of decreased available memory capacity on the ezid-prd database server (see [last 7 month RDS metrics for ezid-prd](https://metrics.librato.com/s/public/azpakcmwd?duration=19954680&source=%2Aezid%2Aprd%2A)). Work with IAS to understand:
1. If this pattern is common, or it is specific to EZID
2. If we can increase the available memory capacity
3. If low available memory capacity affects the EZID application

**Comment by jsjiang** [comment]
Joe (IAS) and Jing reviewed the EZID Prod EC2 and RDS metrics together on 7/21. Here is what we found:
* EZID EC2 (uc3-ezidui02x2-prd.cdlib.org) - There are memory usage pattern changes since 5/17: 
  * before 5/17:  was around 50%
  * from 5/17: jumped to 65%. Note: there were ["Service unavailable" errors on May 17 #424](https://github.com/CDLUC3/ezid/issues/424). 
  * from 5/20: jumped to 75% and is performed at this level since then. There were a few times when the memory usage was close to 100%
  * recommendation: upgrade EC2 to a larger instance with more memory
* RDS Prd - is a m5-large instance with 8GB memory
  * available memory is alway around 500MB - Joe thinks this should be fine. But we can try to upgrade it to larger instance for a short time period and see if it can improve application performance.
 * RDS Dev - is a m5-medium instance with 4GB memory. The available is 2.6GB without EZID    (Stopped EZID to get the baseline)
   * Jing will create some batch jobs in the Dev environment to find out memory usage pattern.

**Comment by marisastrong** [comment]
will upgrade RDS gp3 to more iops to see if issue goes away

**Comment by jsjiang** [comment]
Monitor the system and log 5XX errors weekly [EZID 5XX error log](https://docs.google.com/document/d/1ZB7QK1tsxtVTDWnfe03fc2ym2DG72S3gj_vNGczSYDo/edit?usp=sharing)

**Comment by jsjiang** [comment]
Upgraded  IOPS from 3000 to 4000 on Aug 9, with Notification time : 2023-08-09 23:22:19.544

**Comment by jsjiang** [comment]
Review note ([EZID-PRD Aug 2023 RDS Metrics](https://metrics.librato.com/s/public/azpakcmwd?duration=2419200&source=%2Aezid%2Aprd%2A)):
* IOPS: increased and are operated between 4K to 5K at peak time
* Available storage capacity: increased from 166-> 256 GB
* Disk queue depth: decreased from 20 at peak time to under 5 (Ashley says this is good)
* One issue: we still see decreases with available memory capacity - dropped from 640 to 200 on Aug 19.
