### ISSUE TITLE
Investigate 7/27 Service Unavailable error from Northwestern on id/ark:/81985/n2

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#450]
On 7/27 between 12:30 to 1:30pm,  there were 676 “Service Unavailable” errors triggered from requests from Northwestern on prefix 'id/ark:/81985/n2'. 

The total requests from NW during this time period was 259,671. Average requests was 72 per second.
User agent: nulib-ark-checker/0.1.0
Requests came from multiple IPs: 54.197.28.98, 54.80.191.29, 35.172.201.152, 18.208.160.67, 3.88.193.192 

See [requests on OpenSearch](https://search-os-uc3-logging-stg-suwz42vownvyte6ivqazeifz44.us-west-2.es.amazonaws.com/_dashboards/goto/7f40741c52b3067ae12a3843c572631d?security_tenant=global)

**Comment by jsjiang** [comment]
NWU might have repeated the same process on 7/28. Between 4-5:20pm, there were over 286K requests and 429 requests ended with 502 “Service Unavailable” error.

**Comment by mariagould** [comment]
Closing and addressing via other issues
