### ISSUE TITLE
Upgrade Python to 3.11 for EZID

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#468]
Upgrade Python to 3.11 for EZID.

Review Python release notes:
* [3.9](https://docs.python.org/3.9)
* [3.10](https://docs.python.org/3.10)
* [3.11](https://docs.python.org/3.11/)

Test list:

- [x] GitHub action
- [x] EZID APIs
- [x] EZID UI
- [x] Resolver
- [x] Create minters and shoulders
- [x] Background jobs
- [x] Other management commands
- [x] EZID-Ops scripts in Python
- [x] Performance tests
- [x] Rollback plan in place & tested

**Comment by jsjiang** [comment]
[Status of Python versions](https://devguide.python.org/versions/)
* EZID's current version 3.8.5 will be **end of live 2024-10**
* 3.12 was first released on 2023-10-24 and is in bug-fix status
* 3.11 was first release on 2022-10-24 and is in security status, end of live 2027-10

**Comment by jsjiang** [comment]
The last bugfix release of the Python 3.11 series: 3.11.9
Release date: April 2, 2024

- Downloadable files: https://www.python.org/downloads/release/python-3119/
- Release doc: https://docs.python.org/release/3.11.9/

**Comment by jsjiang** [comment]
@ashleygould Hi Ashley, can you create a Python 3.11.9 virtual environment on ezid-dev for testing.  
Thank you

Jing

**Comment by jsjiang** [comment]
On my local Mac:

Install Python 3.11.9
```
pyenv install 3.11.9
cd ezid-dev/ezid
pyenv local 3.11.9 (or ask VS Code to use 3.11.9)
pip install -r requirements-dev.txt
```

Prepare test database
```
./prepare_test_db.sh
```
Run tests
```
pytest --ds=settings.tests  tests
```

**Comment by ashleygould** [comment]
This is from a slack chat with Jing.  I'm including it here for context:
```
[4:42 PM](https://cdlib.slack.com/archives/D04MRT68FAM/p1715730162469609)
ansible task configure_ezid is failing when running setup.py.  here is snippet:

TASK [ezid : run setup.py] ***************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/ezid/.pyenv/versions/3.11.9/bin/python", "/ezid/ezid/setup.py", "develop"], "delta": "0:05:20.448763", "end": "2024-05-14 16:27:02.171546", "msg": "non-zero return code", "rc": 1, "start": "2024-05-14 16:21:41.722783", "stderr": "/ezid/.pyenv/versions/3.11.9/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.\n  warnings.warn(\n/ezid/.pyenv/versions/3.11.9/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.

This is after commenting out my KLUGE tasks I added last month to get this to run on AL2023, which were also failing.When I run git list, I see a very long set of deprication warning like this one:

ezid@uc3-ezidui-dev01:16:32:33:~$ pip list
DEPRECATION: Loading egg at /apps/ezid/.pyenv/versions/3.11.9/lib/python3.11/site-packages/billiard-4.2.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330

The recommended solution on the provided link is

pip has dropped support for installing .egg distributions when it stopped invoking setup.py install.
At some point pip will abandon support for detecting and uninstalling legacy .egg distributions too.

If you reach this issue from the pip deprecation message, it is likely that your Python environment has distributions that have been installed with setup.py install, easy_install, or an older pip version.

The recommended action is to uninstall the distribution and reinstall it with a recent pip.
```

The take away is we need to upgrade our deployment process which still uses `setup.py` to install packages.  We are now exploring `poetry`.

**Comment by ashleygould** [comment]
Initial draft of poetry config file `pyproject.toml` based on existing `requirements.txt` and `setup.py`: 
https://github.com/CDLUC3/ezid/blob/poetry-ashley/pyproject.toml

**Comment by jsjiang** [comment]
We changed to use `Poetry` (with `pyproject.toml` and `poetry.lock` ) to manage package dependencies since June 2024. Here is the new procedure for setup my local dev environment on Mac:

1. Create Python 3.11.9 virtual environment using `pyenv`
```
pyenv install 3.11.9
pyenv virtualenv 3.11.9 ezid-py311
pyenv global ezid-py311 
```
2. Run `pip install .`. This tells pip to source file `pyproject.toml` and install all dependencies listed in table `[tool.poetry.dependencies]`
```
pip install .
```

3. Validate installed packages against poetry.lock file
```
poetry check --lock
All set!
```

4. Check deprecated modules and  functions using the `python -Wd` otpion

```
 python -Wd manage.py runserver
Performing system checks...

/Users/jjiang/my_dev_space/ezid-dev/ezid/impl/api.py:86: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
/Users/jjiang/my_dev_space/ezid-dev/ezid/impl/form_objects.py:75: DeprecationWarning: invalid escape sequence '\d'
  REGEX_4DIGITYEAR = '^(\d{4}|\(:unac\)|\(:unal\)|\(:unap\)|\(:unas\)|\(:unav\)|\
/Users/jjiang/my_dev_space/ezid-dev/ezid/impl/form_objects.py:77: DeprecationWarning: invalid escape sequence '\d'
  REGEX_GEOPOINT = '-?(\d+(\.\d*)?|\.\d+)$'
/Users/jjiang/my_dev_space/ezid-dev/ezid/ui_tags/templatetags/manage_form_tags.py:45: DeprecationWarning: invalid escape sequence '\>'
  + " \> "
System check identified no issues (0 silenced).
September 12, 2024 - 10:36:10
Django version 4.2.16, using settings 'settings.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

**Comment by jsjiang** [comment]
Review deprecated modules and functions:

1. DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13. 

The `is_text_plain_utf8` function in `impl/api.py` uses the `cgi.parse_header()` function to get the mimetype and charset.  Find a replacement now or when we upgrade to Python 3.13.
```
def is_text_plain_utf8(request):
    content_type = request.META.get('CONTENT_TYPE', '')
    mimetype, options = cgi.parse_header(content_type)
    if mimetype not in ('text/plain', ''):
        return False
    if options.get('charset', 'utf-8').lower() != 'utf-8':
        return False
    return True
```

It is recommended to use the `email` package (https://docs.python.org/3/library/cgi.html)
```
cgi.parse_header(string)
Parse a MIME header (such as Content-Type) into a main value and a dictionary of parameters.

Deprecated since version 3.11, will be removed in version 3.13: This function, like the rest of the [cgi](https://docs.python.org/3/library/cgi.html#module-cgi) module, is deprecated. It can be replaced with the functionality in the [email](https://docs.python.org/3/library/email.html#module-email) package, which implements the same MIME RFCs.

For example, with [email.message.EmailMessage](https://docs.python.org/3/library/email.message.html#email.message.EmailMessage):

from email.message import EmailMessage
msg = EmailMessage()
msg['content-type'] = 'application/json; charset="utf8"'
main, params = msg.get_content_type(), msg['content-type'].params
```

2. DeprecationWarning: invalid escape sequence reported in `/ezid/impl/form_objects.py` and `ezid/ui_tags/templatetags/manage_form_tags.py` - fix and test

Note: use code analysis tools such as `pylint` , `flake8` and `flake8-deprecated` to identify deprecated or removed functions and modules.

**Comment by jsjiang** [comment]
Deployment plan:
* Deregister the targeted EC2 instance from the load balancer (ref: https://ucopedu.atlassian.net/wiki/spaces/UC3/pages/45427589/Register+Deregister+EC2+Instances+with+ALB+TargetGroup)
* logon to the EC2 instance (prd01 or prd02) as the `uc3puppet` account
* disable the `uc3_pupapply.sh` cron job
* update the deployment configuration files in `uc3-ops-puppet-hiera.git` repo
  * `fqsn-os/uc3-ezid-ui-prd-2023.yam`l: update Python virtual environment variables
  * `node/uc3-ezidui-prd01.cdlib.org.yaml`: update Python virtual environment variables + disable run_ansible
* commit changes to `uc3-ops-puppet-hiera.git` repo
* logon to the EC2 instance  as the `uc3puppet` account
* run the `uc3_pupapply.sh` and then `uc3_pupapply.sh --exec` command to update the `ansible_extra_vars.yaml` file
* logon to EC2 as `ezid`
* run ansible-playbook commands with extra-args from `ansible_extra_vars.yaml` file
  * cd ~/install/ezid/ansible
  * view configuration in `ansible_extra_vars.yaml` file
  * if configuration looks good, try run the ansible-playbook command
  * then run the ansible-playbook command for real
 * Verify Python version environment: `pyenv versions`
 * use the `sudo cdlsysctl` command to start the `ezid` and background jobs (identified by `ezid-proc-*`)
* test ezid
* if everything looks fine, update the deployment configuration files in `uc3-ops-puppet-hiera.git` repo to use the new tag (`python-test` or equivalent )
* change `run_ansible` back to `true`
* commit the change to `uc3-ops-puppet-hiera.git` repo
* logon on the EC2 instance as `uc3puppet`
* run the `uc3_pupapply.sh` and then `uc3_pupapply.sh --exec` command to deploy the new tag
* test ezid
* register the targeted EC2 instance to the load balancer

```
# dry-run ansible-playbook with extra vars
ansible-playbook -i hosts site.yaml -e @ansible_extra_vars.yaml -C -D
#
# for reals
ansible-playbook -i hosts site.yaml -e @ansible_extra_vars.yaml
```

Sample crontab on ezid-prd01
```
cruc3puppet@uc3-ezidui-prd01:~> crontab -l
MAILTO="agould@ucop.edu"
#Ansible: run puppet apply
49 * * * * /apps/uc3puppet/bin/uc3_pupapply.sh --quiet --exec
```

Update deployment configuration files:
```
    run_ansible: true
    virtual_environments:
    - python_version: '3.8.5'
      pyenv_name: 'ezid-py3'
    pyenv_global: 'ezid-py3'
```
To:
```
    run_ansible: false
    virtual_environments:
    - python_version: '3.11.9'
      pyenv_name: 'ezid-py311'
    pyenv_global: 'ezid-py311'
```

**Comment by jsjiang** [comment]
Testing shoulder, minter and management commands:

```
python manage.py shoulder-mint ark:/99999/fk4
python manage.py shoulder-mint ark:/99999/fk4 -c 2
python manage.py shoulder-mint ark:/99999/fk4 -u
python manage.py shoulder-mint ark:/99999/fk4 -c 10

python manage.py shoulder-create-ark ark:/99999/jj1 "jing test shoulder"
python manage.py shoulder-mint ark:/99999/jj1
python manage.py shoulder-mint ark:/99999/jj1 -c 10

python manage.py shoulder-list --debug

 python manage.py diag-queue-stats
```

**Comment by jsjiang** [comment]
Rollback plan:
* modify the deployment configuration files (node/uc3-ezidui-<instance>.cdlib.org.yaml and fqsn-os/uc3-ezid-ui-<instance>-2023.yaml) to use Python 3.8.5
```
    virtual_environments:
    - python_version: '3.11.9'
      pyenv_name: 'ezid-py311'
    pyenv_global: 'ezid-py311'
    - python_version: '3.8.5'
      pyenv_name: 'ezid-py3'
    pyenv_global: 'ezid-py3'
```
* run ` uc3_pupapply.sh --exec` to deploy EZID
* verify Python version (pyenv versions)
* verify EZID application

* Rolled back to Python 3.8.8 & tested on ezid-stg
* Redeployed Python 3.11.9 to ezid-stg

**Comment by jsjiang** [comment]
Test resolver functionalities:

https://ezid-stg.cdlib.org/id/ark:/99999/fk4mw4013g => identifier info in EZID UI

https://ezid-stg.cdlib.org/ark:/99999/fk4mw4013g?? => metadata

https://ezid-stg.cdlib.org/ark:/99999/fk4mw4013g => Google page (https://www.google.com/)

**Comment by jsjiang** [comment]
Load tests on ezid-stg 2024-03-27:
* test script: ezid_mint_with_data.py
* Number of users: 15
* Requests per Second (RPS): 16.3
* Response time: 95%ile (ms): 4100

![Image](https://github.com/user-attachments/assets/1150af6f-4cd7-4c80-954d-b3599fe36217)

Load tests on ezid-stg 2024-09-20 (with py311):
* test script: ezid_mint_with_data.py
* Number of users: 15
* Requests per Second (RPS): 19.6
* Response time: 90%ile (ms): 2100

![Image](https://github.com/user-attachments/assets/0311b347-776e-4656-a028-c2687ef00318)

Note:
* No performance decline compare to the March 27 load tests
* The March 27 load tests report is a little bit old. Ideally we should perform load tests right before and after making the changes, then compare the two test results.

**Comment by jsjiang** [comment]
Prd deployment:
* started: 9:10am Sept 23
* health check: 
  * `python verify_ezid_after_patching.py -e prd`: no issue
  * RDS Librato: no issue
  * RDS Performance insights: 
    * the link checker report was started at 8:15am this morning and is still running - this report was last ran on Monday Sept 16 when we deployed `v3.2.22`. It rescheduled itself to run after 7 days. So the job was started this morning from 8:15am. The report first collects qualified records, then checks URL and update status for each collected record. The whole process takes a few hours to finish. It is better not to terminate this report while it is running. 
  * EC2: no issue
  * postpone the deployment to a later time after the link checker report has finished.

**Comment by jsjiang** [comment]
Python version after upgrade:
```
  system
  3.8.5
  3.8.5/envs/ezid-py3
  3.9.11
  3.9.11/envs/ezid-py311
  ezid-py3 --> /ezid/.pyenv/versions/3.8.5/envs/ezid-py3
* ezid-py311 --> /ezid/.pyenv/versions/3.9.11/envs/ezid-py311 (set by /ezid/.pyenv/version)
* ```

**Comment by jsjiang** [comment]
Post update tests :
* running `ec2-tg-status.sh` command shows both instances are in healthy status
* regression tests `python verify_ezid_after_patching.py -e prd` - no issue
* UI tests `python ezid_ui_tests.py -e prd` - no issue
* Resolver tests - no issue

Resolver tests:
* https://ezid.cdlib.org/id/ark:/12345/fk1234 - Identifier page
* https://ezid.cdlib.org/ark:/12345/fk1234?? - metadata info
* https://ezid.cdlib.org/ark:/12345/fk1234 - redirect to CDL services page

**Comment by jsjiang** [comment]
Load tests: no noticeable decreases

Load tests on 2024-09-20 on Python 3.8
* test script: ezid_mint_with_data.py
* Number of users: 15
* Requests per Second (RPS): 34.4
* Response time: 95%ile (ms): 880

![Image](https://github.com/user-attachments/assets/a48c06d4-dfbf-44e7-a48f-bc197836c083)

Load tests on 2024-09-23 on Python 3.11
* test script: ezid_mint_with_data.py
* Number of users: 15
* Requests per Second (RPS): 34
* Response time: 95%ile (ms): 780

![Image](https://github.com/user-attachments/assets/0b9e4082-8d11-4332-8d21-5009f9f9d360)

**Comment by jsjiang** [comment]
Created ticket [742 to upgrade Python packages](https://github.com/CDLUC3/ezid/issues/742)
