### ISSUE TITLE
Import Google Analytics into Matomo

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#480]
For a Google Analytics import into Matomo we need to

- [x] @marisastrong provide Joel access to the GA property, or you can just give him its Account ID, Property ID and View ID, which are listed in the GA property.
- [x] provide date in the past you'd like the import to start with.  import's end date will be whatever day we start the import, but I can also set this to a past date as well. 
- [x] work with Eric to obtain access to the new Matomo property once it's available.

**Comment by marisastrong** [comment]
Thank you @JoelCDL 

I'm not sure how to view this data.  Do we need to configure something with the siteID?

**Comment by rushirajnenuji** [comment]
Thank you @JoelCDL!

@marisastrong  @JoelCDL  -- I think we will need access to this `site ID`. On the `matomo.cdlib.org` I only have access to `SITE_ID: 21` (currently being used in prod for tracking), but when I updated the `SITE_ID` to `34`  in the URL, it gave me the following error:

<img width="590" alt="Matomo error: You can't access this resource as it requires 'view' access for the website id = 34." src="https://github.com/CDLUC3/ezid/assets/19696935/dd0244d0-b8c4-4105-a98f-78eb03135f14">

**Comment by JoelCDL** [comment]
Sorry, I forgot to give you both access to that data. You should now see it in your Matomo dashboards and it's labeled "ezid.cdlib.org - UA Archive".

**Comment by rushirajnenuji** [comment]
Confirming the access to `ezid.cdlib.org - UA Archive`, thank you again @JoelCDL  -- this is very helpful!
