### ISSUE TITLE
Load test EZID and Resolver integration

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#481]
EZID has about 1.8 million requests each month. Current N2T has about 3-4 million requests on ARKs each month. Perform  load tests in the EZID-Stg environment to learn if adding ARK resolver service to EZID would cause performance issue.

**Comment by datadavev** [comment]
load testing by @jsjiang and @datadavev indicates that EZID is unlikely to be adversely impacted when resolution is handed off to EZID.
