### ISSUE TITLE
Investigate orphan Berkeley DB files

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#483]
There are some Berkeley DB (minter) files that do not have corresponding shoulder entries in the  EZID database. Review these minters and decide if any of them need  to be migrated to MySQL database.

**Comment by jsjiang** [comment]
Prefixes/shoulders for the orphan BDB minter files:
1.  ark:/77913/r7
* nog file timestamp on ezid server: May 20  2022
* minter metadata: 
```
when:      2020.06.23_17:55:51
where:     ids-n2t2-prd:./minters/ezid/ark/77913/r7
Version:   Nog 1.00
```

2. ark:/83018/g4
* nog file timestamp on ezid server: May 20  2022
* minter metadata: 
```
when:      2020.06.23_17:56:23
where:     ids-n2t2-prd:./minters/ezid/ark/83018/g4
Version:   Nog 1.00
```

3. ark:/85783/c9
* nog file timestamp on ezid server: May 20  2022
* minger metadata:
```
when:      2020.06.23_17:56:49
where:     ids-n2t2-prd:./minters/ezid/ark/85783/c9
Version:   Nog 1.00
```
5. 86076/j6 
* nog file timestamp on ezid server: May 20  2022
* minger metadata:
```
when:      2020.06.23_17:56:52
where:     ids-n2t2-prd:./minters/ezid/ark/86076/j6
Version:   Nog 1.00
```
7. 86084/m8 
* nog file timestamp on ezid server: May 20  2022
* minger metadata:
```
when:      2020.06.23_17:56:54
where:     ids-n2t2-prd:./minters/ezid/ark/86084/m8
Version:   Nog 1.00
```
9. 87920/f9   
* nog file timestamp on ezid server: May 20  2022
* minger metadata:
```
when:      2020.06.23_18:04:16
where:     ids-n2t2-prd:./minters/ezid/ark/87920/f9
Version:   Nog 1.00
```

[Initial  analysis document](https://docs.google.com/spreadsheets/d/16Ackl8rs2hsXJuMPjUzlZWsNIkDYWPiGpb2Ha1f3KKE/edit#gid=0)

**Comment by mariagould** [comment]
All of these shoulders were originally associated with former EZID users:

ark:/77913/r7: Originally associated with regenbase project at University of Miami (former EZID user)
ark:/83018/g4: Originally associated with globus project at U Chicago (former EZID user)
ark:/85783/c9: Originally associated with dartcrawda project at Dartmouth (former EZID user)
ark:/86076/j6: Originally associated with Fred Hutchinson account (former EZID user)
ark:/86084/m8: According to old email records, this was associated with Figshare (former EZID user)
ark:/87920/f9: Originally associated with cams account at U of Florida (former EZID user)

I suspect they may have been deleted with the users canceled their accounts. I will do some more investigation on my end.

**Comment by mariagould** [comment]
My assessment of this situation is that we do not need to migrate the minters because the accounts are no longer active and have not been active for many years now.

**Comment by jsjiang** [comment]
ark:/90135/q1 
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:06:24

ark:/99999/NULL, ark:/99999, or ark:/99999/
* nog file last updated: May 20  2022
* minter created timestamp: need to be extracted from the nog.bdb file

ark:/99999/df4
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:06:24

ark:/99999/ffk4
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.09_16:46:17

ark:/99999/fk5
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:21:09

ark:/99999/fk88
* nog file last updated: May 20  2022
* minter created timestamp: need to be extracted from the nog.bdb file

doi:10.5060/d2
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:21:10

doi:10.b5060/d8
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:21:10

doi:10.5070/NULL
* nog file last updated: May 20  2022
* minter created timestamp: need to be extracted from the nog.bdb file

doi:10.5072/NULL
* nog file last updated: May 20  2022
* minter created timestamp: need to be extracted from the nog.bdb file

doi:10.5072/ffk2
* nog file last updated: May 20  2022
* minter created timestamp:  2020.06.09_16:46:18

doi:10.5072/fk22 
* nog file last updated: May 20  2022
* minter created timestamp: need to be extracted from the nog.bdb file

doi:10.5072/fk7
* nog file last updated: May 20  2022
* minter created timestamp: need to be extracted from the nog.bdb file

doi:10.5811/NULL - super shoulder without minter; 
* nog.bdb file last updated: **Apr 27 16:10**
* the nog file should not have been created when creating the shoulder (programming bug)

doi:10.5967/k9
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:30

doi:10.6076/j7 
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:33

doi:10.6084/m9
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:35

doi:10.7273/q9
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:42

doi:10.7920/f8
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:49

doi:10.13015/j4
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:53

doi:10.13018/g2 
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:53

doi:10.15783/c7 
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:58

doi:10.17607/c6
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:58

doi:10.17913/NULL
* nog file last updated: Nov 21  2022
* minter created timestamp: ?

doi:10.17913/r3
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:22:59

doi:10.17953/NULL - a super shoulder created on 2023-02-15; this shoulder does not have a minter. So the bdb file should not have been created.
* nog file last updated: Feb 15  2023
* minter created timestamp:

doi:10.18114/p5 
* nog file last updated: May 20  2022
* minter created timestamp:

doi:10.18434/v4
* nog file last updated: May 20  2022
* minter created timestamp: 2020.06.23_18:23:02



f1223/fk3

f2942/NULL    

f9999/c5       

f9999/sd2      
 
g6867/NULL

**Comment by mariagould** [comment]
Notes from my review:

ark:/90135/q1
Shoulder previously associated with now-defunct University of New Mexico / ONEShare account

ark:/99999/NULL, ark:/99999, or ark:/99999/
This is the NAAN for testing. I suspect these were used for testing in the past. 

ark:/99999/df4
This is the NAAN for testing. I suspect this was used for testing in the past. 

ark:/99999/ffk4
This is the NAAN for testing. I suspect this was used for testing in the past. 

ark:/99999/fk5
This is the NAAN for testing. I suspect this was used for testing in the past. 

ark:/99999/fk88
This is the NAAN for testing. I suspect this was used for testing in the past. 

doi:10.5060/d2
This prefix is no longer owned or used by CDL. 

doi:10.5060/d8
This prefix is no longer owned or used by CDL. 

doi:10.5070/NULL
I don't know anything about this but it's our generic Crossref prefix used for most journal articles. 

doi:10.5072/NULL
This is the prefix for testing DataCite DOIs. I suspect this was used for testing in the past. 

doi:10.5072/ffk2
This is the prefix for testing DataCite DOIs. I suspect this was used for testing in the past. 

doi:10.5072/fk22
This is the prefix for testing DataCite DOIs. I suspect this was used for testing in the past. 

doi:10.5072/fk7
This is the prefix for testing DataCite DOIs. I suspect this was used for testing in the past. 

doi:10.5811/NULL - super shoulder without minter;
Active prefix. Shoulder does not require minter. 

doi:10.5967/k9
Prefix no longer in use

doi:10.6076/j7
Active prefix but I don't know anything about this shoulder

doi:10.6084/m9
Prefix no longer in use

doi:10.7273/q9
Prefix no longer in use

doi:10.7920/f8
Prefix no longer in use

doi:10.13015/j4
I don't have any information about this

doi:10.13018/g2
Prefix no longer in use

doi:10.15783/c7
Prefix no longer in use

doi:10.17607/c6
Prefix no longer in use

doi:10.17913/NULL
Active prefix but I don't know anything about this shoulder

doi:10.17913/r3
Active prefix but I don't know anything about this shoulder

doi:10.17953/NULL - a super shoulder created on 2023-02-15; this shoulder does not have a minter. So the bdb file should not have been created.
This is meant to be a super-shoulder used for registering eScholarship DOIs. No minter is required. 

doi:10.18114/p5
Prefix no longer in use

doi:10.18434/v4
Prefix no longer in use

doi:10.31223/fk3
I suspect this might have been used for testing preprints. 

doi:10.32942
Prefix actively used for preprints but I don't know anything about this shoulder

doi:10.39999/c5
Prefix no longer in use

doi:10.39999/sd2
Prefix no longer in use

g6867/NULL
I don't know what this refers to
