### ISSUE TITLE
Leverage Matomo to trigger metrics via server side call

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#489]
Need to check if we can send events to Matomo from the server side. This would be helpful for tracking API requests for example, which would never be triggered otherwise.

**Comment by marisastrong** [comment]
There is some support for server-side tracking, but may not be in current development.  I was able to find a few resources.

https://developer.matomo.org/guides/tracking-api-clients#client-libraries-for-apps-or-server-side-tracking
https://matomo.org/integrate/#programming-language-platforms-and-frameworks
https://github.com/matomo-org/piwik-python-api/tree/master - Python version of server-side tracking library

**Comment by datadavev** [comment]
Related to #548 which is investigating a possible path for implementation of this functionality.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/V3.2.5.
