### ISSUE TITLE
Minter Migration Rollback plan

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid#490]
Summary: This ticket outlines the checklist for the migration of the EZID service from Berkeley Database (BDB) to MySQL. The migration is being performed to support scaling and improve the performance of the application.

Lead: @jsjiang  

Schedule: _**tbd**_

Status: **_draft_**

Pre-Upgrade (prepare for upgrade)
- [ ] ...

Upgrade (upgrade database and application)

- [ ] ...

Post-Upgrade (verify operation)

- [ ] ...

Roll back / recovery plan: [link](https://hackmd.io/@nenuji/HkuS-R8z6/edit)

**Comment by rushirajnenuji** [comment]
Reference to previous migration checklists:
[EZID Stage 3 upgrade checklist](https://github.com/CDLUC3/ezid/issues/257)
[Verify upgrade procedure and document the exact steps for the upgrade to python 3 for all environments](https://github.com/CDLUC3/ezid/issues/147)

**Comment by jsjiang** [comment]
Parent ticket #87

**Comment by rushirajnenuji** [comment]
Added to internal docs: [EZID Roll back Plan](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/rollback.md)
