### ISSUE TITLE
daylight savings time is ending - time to change maintenance window to match

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#492]
Nov 5, 2023, we need to inform IAS to move our maintenance window for RDS back an hour.  I couldn't find the ticket for this from the last time this occurred.

**Comment by jsjiang** [comment]
Here is the [CDLSys ticket](https://github.com/cdlib/cdlsys/issues/35)

**Comment by marisastrong** [comment]
done and next time we will need to file a new ticket with IAS.
