### ISSUE TITLE
Update EZID-is-Down page content

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#507]
Currently we have:

EZID is down for maintenance

EZID's regularly scheduled maintenance window is Thursday [5:00am](http://www.thetimezoneconverter.com/?t=5:00am&tz=Oakland)–[6:00am](http://www.thetimezoneconverter.com/?t=6:00am&tz=Oakland) Pacific time.

**Comment by jsjiang** [comment]
@mariagould Hi Maria, please provide new content so I can update the code.  Thank you!

**Comment by mariagould** [comment]
**EZID is down for maintenance**

EZID's regularly scheduled maintenance window is Thursday [5:00am](http://www.thetimezoneconverter.com/?t=5:00am&tz=Oakland)–[6:00am](http://www.thetimezoneconverter.com/?t=6:00am&tz=Oakland) Pacific time. For more information on system availability, check [EZID's status page](https://ezidstatus.wordpress.com/).

**Comment by jsjiang** [comment]
* Modified tools/downserver.py to use the updated page content.
* Tested on ezid-dev

**Comment by jsjiang** [comment]
@rushirajnenuji Hi Rushiraj, the updated content is in the "87_Berkeley_DB_migration" branch. Can you check it out on ezid-dev and test. Let me know if you notice any issues. 

Thank you

Jing
