### ISSUE TITLE
Document Cookies that are tracked

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/ezid#529]
For our updated privacy policy, we will be providing information about cookies each service/application is tracking.

This spreadsheet is being used to track which cookies are used for each service. Please update the spreadsheet for EZID.

Note different cookies are tracked when a user logs in so we need to be inclusive of all cookies that are tracked.

https://docs.google.com/spreadsheets/d/1puytJGa2-yqkS0zM2fBgs6BOV0vdS03M3TkR5wXlgKE/edit#gid=0

**Comment by sfisher** [comment]
These are the cookies I see while logged out.  I believe both of the `_ga` cookies are Google analytics. Is EZID still using Google Analytics?  I thought it had transitioned to Matomo?  `impl/ui_common.py` seems to set some variables for GA and the base layout seems to set up the Javascipt for it. `templates/layouts/base.html`

One of the `_pk` cookies seems to be a boolean (a 1) which maybe tracks if a session is used?

The other seems to contain some kind of id which I believe means that ID is passed back and forth for the session which is used by application to maintain state between pages.  To really know what is being tracked, we then need to look at items stored in the session for various states (logged in or not) to know what's being tracked.

![Screenshot 2023-12-13 at 3 49 31 PM](https://github.com/CDLUC3/ezid/assets/105433/38047fd5-d235-46d6-8b05-6e4bd2ea3073)
