### ISSUE TITLE
Document DataCite schema upgrade process

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#538]
The process for upgrading to a new version of the DataCite metadata schema is not currently documented. In order to support knowledge sharing and knowledge transfer across the development team, the process should be documented. This documentation should be stored with other EZID docs on Github. 

This should be done in tandem with #511

**Comment by jsjiang** [comment]
Started a GitHub page on [How to upgrade DataCite Schema](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/how_to_upgrade_datacite_schema.md)

**Comment by jsjiang** [comment]
[Schema 4.4 -> 4.5 upgrade notes](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/how_to_upgrade_datacite_schema.md)
