### ISSUE TITLE
Fix binder queue

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#54]

**Comment by rushirajnenuji** [comment]
Environment: EZID Stage 2
Deployed Branch: [ezid-minter](https://github.com/CDLUC3/ezid/tree/ezid-minter)

**Configuration settings**
Configuration for forwarding the identifiers to the N2T resolver:

Things that I've verified so far
- [ ] Verify that the binder daemon is enabled. (looks okay - [here](https://github.com/CDLUC3/ezid/blob/ezid-minter/settings/ezid.conf#L69))
- [ ] Verify that correct endpoints are configured in the binder settings. (verified with John K. looks okay - [here](https://github.com/CDLUC3/ezid/blob/ezid-minter/settings/ezid.conf#L104))
- [ ] Verify that the shadow file contains correct credentials to talk to N2T (verified)


**Binder Queue Stats**
To check the status of the binder queue - 
```
~/ezid/tools$ ./queue-admin binder overview
entries: 64
earliest: 2020-09-08T10:21:57
latest: 2020-10-06T10:44:18
permanent errors: 46
transient errors: 0
```

To review the existing entries in the queue that errored out:
```
~/ezid/tools$ ./queue-admin binder list-perrors
```


To retry forwarding the existing entries to N2T, clear the permanent error flag
```
~/ezid/tools$ ./queue-admin binder clear-perrors
```

**Errors observed**
```
- Exception: noid_egg.setElements error: HTTPError: HTTP Error 401: Unauthorized (2 identifiers)
- Exception: noid_egg.batchSetElements error: HTTPError: HTTP Error 401: Unauthorized (44 identifiers)
```
