### ISSUE TITLE
DataCite: Deprecating Metadata Schema 3

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid#559]
Hi all, this came to my attention this week, so filing a ticket in here.

The official [announcement](https://datacite.org/blog/deprecating-schema-3/) from DataCite.

Key points from the announcement:
`deadline`: January 1, 2025
`update procedure`: [link](https://support.datacite.org/docs/updating-from-schema-3-to-schema-4)

There is also a webinar hosted by DataCite on March 13, 2024. [sign up link](https://datacite.zoom.us/rest/webinar/registrant/WN_vpz1MT1FSmujinjWgh3mtQ/info?tk=VD6nWeQHi0GruzspNcM6238VC-GFt1NgHRfLddmTQTArXpdFWgPvVbc.KPwYjAczHRyCYUhy&ac=approved&timezone_id=America/Los_Angeles#/registration)

To get stats on IDs with Schema 3 versions for a specific repository (e.d.`cdl.cdl`) is as follows: 
```curl
curl --location 'https://api.datacite.org/dois?client-id=cdl.cdl&schema-version=3'
```

The meta tag in the response has useful some stats:
```json
        "providers": [
            {
                "id": "naqr",
                "title": "California Digital Library",
                "count": 3567
            }
        ],
        "clients": [
            {
                "id": "cdl.cdl",
                "title": "California Digital Library",
                "count": 3567
            }
        ],
        "affiliations": [],
        "prefixes": [
            {
                "id": "10.15144",
                "title": "10.15144",
                "count": 3510
            },
            {
                "id": "10.7293",
                "title": "10.7293",
                "count": 44
            },
            {
                "id": "10.5060",
                "title": "10.5060",
                "count": 13
            }
        ],
        "certificates": [],
        "licenses": [
            {
                "id": "cc-by-sa-4.0",
                "title": "CC-BY-SA-4.0",
                "count": 3083
            }
        ],
        "schemaVersions": [
            {
                "id": "3",
                "title": "Schema 3",
                "count": 3567
            }
        ],
        ...
```

However, it would be useful to get these stats fro our database as well to be thorough.

**Comment by rushirajnenuji** [comment]
More on DataCite API [queries and filtering](https://support.datacite.org/docs/api-queries)

**Comment by jsjiang** [comment]
Closing this ticket. Use #540
