### ISSUE TITLE
Setup High Availability for EZID

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#562]
Setup High Availability for EZID:

- [x] refactor puppet module

- [x] deploy uc3-ezid-ui-dev
  - [x] new ALB/TG for uc3-ezid-ui-dev
  - [x] request 1 al2023 dev instance
  - [x] build out ezid service on new ec2 instance
  - [x] place al2023 instance into ALB TG
  - [x] remove al2 instance from ALB TG
  - [x] validate service at https://uc3-ezid-ui-dev.cdlib.org
  - [x] request dns domain cutover ezid-dev.cdlib.org -> new ALB
  - [x] update nagios configs
  - [x] decommision old al2 instance
  - [x] clean up puppet configs
- [x] deploy uc3-ezid-ui-stg
   - [x] request 2 al2023 stg instances
   - [x] build out ezid service on new ec2 instances
   - [x] place al2023 instances into ALB TG
   - [x] remove al2 instance from ALB TG
   - [x] validate service at https://ezid-stg.cdlib.org
   - [x] configure background procs on only one of the new instances
   - [x] remove background procs on old al2 instance
   - [x] update nagios configs
   - [x] decommision old al2 instances
   - [x] clean up puppet configs
- [x] deploy uc3-ezid-ui-prd
   - [x] request 2 al2023 prd instances
   - [x] build out ezid service on new ec2 instances
   - [x] place al2023 instances into ALB TG
   - [x] remove al2 instance from ALB TG
   - [x] validate service at https://ezid.cdlib.org
   - [x] configure background procs on only one of the new instances
   - [x] remove background procs on old al2 instance
   - [x] update nagios configs
   - [x] decommision old al2 instances
   - [x] clean up puppet configs

**Comment by jsjiang** [comment]
* Ashley and Jing met and drafted [the EZID HA work plan](https://docs.google.com/document/d/18cb2XQDXNRZa8L-7b7votsKKmumsFdaTKsT8doDBgtk/edit?usp=sharing)
* Share the work plan with the EZID team for feedbacks.

**Comment by jsjiang** [comment]
Task 1: Build EZID-DEV environment with Linux 2023, SSL and HA:
* Build a Linux 2023 EC for dev
* Create ALB for Dev environment, include SSL
* Build the 2nd 2023 Dev box
* Setup EZID
* Test EZID

**Comment by ashleygould** [comment]
new ec2 instance and ALB for uc3-ezid-ui-dev have been provissioned by IAS.  I will validate and deploy ezid ui service this week.

**Comment by ashleygould** [comment]
new infrastructure for uc3-ezid-ui-dev is fully provissioned with app deployed.  We only need to migrate DNS domain `ezid-dev.cdlib.org` to resolve to the new infrastructure.

**Comment by ashleygould** [comment]
new hosts for uc3-ezid-ui-stg are provssioned.  working on app deployment now.

**Comment by marisastrong** [comment]
Stage environment is complete.  Stage will have 2 hosts that go behind the ALB.  The domain is already pointing to the ALB
- [ ]  add the AL 2023 host to the stage ALB

**Comment by jsjiang** [comment]
Validate ezid-stg service #602

**Comment by jsjiang** [comment]
- [ ] decommision old al2 instance #605
