### ISSUE TITLE
Stop the proc-binder job after N2T migration

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#563]
There is no need to send the ARK's metadata to N2T anymore after the N2T migration. 
* Ashley update deployment scripts to remove the proc-binder from the background jobs
* decommission the proc-binder.py command - EZID developer
* stop writing records to the binder queue

**Comment by adambuttrick** [comment]
@jsjiang This appears to the the last task on https://github.com/CDLUC3/ezid/issues/582. Is this still running or has it been disabled? If still running, how do we identify when we should disable?

**Comment by jsjiang** [comment]
@adambuttrick We need to wait until Dave says it is ok to stop the old N2T instances and services.

**Comment by marisastrong** [comment]
- [ ] Jing to check whether as part of this process anything gets updated in the record after communicating with N2T
- [ ] Next step would also involve stopping writing these jobs to the queue

**Comment by datadavev** [comment]
I have verified that the the new N2T and ARK resolver services have no dependency on updates to the legacy-n2t identifier database.

**Comment by jsjiang** [comment]
Note:
1. The record status in binder queue status gets updated after communicating with N2T:
* success: set to 'O'
* failure: set o 'F'
* the initial status is 'U'

2. EZID code to update:
* enqueue.py: remove BinderQueue from the queue_model_list
* proc-binder.py: delete
* proc-cleanup-async-queues.py (remove identifiers from refidentifier table once all required actions are finished)

3. Remove proc-binder from systemd/cdlsysctl command

**Comment by jsjiang** [comment]
@ashleygould 
Hi Ashley, we can stop the `proc-binder` job now. Can you remove it from the EZID deployment process, the `cdlsysctl` command and Nagios monitoring lists.  
Thank you

Jing

**Comment by ashleygould** [comment]
I'll do this monday morning.

**Comment by ashleygould** [comment]
ezid-proc-binder service is removed from both stage and production background tasks.  I have put is a request for IAS to update nagios configs accourdingly.

**Comment by marisastrong** [comment]
[like]  Marisa Strong reacted to your message:
________________________________

**Comment by jsjiang** [comment]
> ezid-proc-binder service is removed from both stage and production background tasks. I have put is a request for IAS to update nagios configs accourdingly.

Thank you Ashley!
