### ISSUE TITLE
Deploy EZID on the Linux 2023 EZID Dev servers

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#571]
Deploy EZID on the Linux 2023 EZID Dev servers

**Comment by ashleygould** [comment]
The infrastructure is ready. current url: https://uc3-ezid-ui-dev.cdlib.org

we still need to change DNS such that ezid-dev.cdlib.org resolves to the new infrastructure

**Comment by ashleygould** [comment]
dns change requested.

**Comment by ashleygould** [comment]
dns change complete
