### ISSUE TITLE
Disable public access to the download folder

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#576]
The public access point "https://ezid.cdlib.org/download/" is not needed anymore as we use the S3 bucket for batch download now. The access point is mapped to the "/apps/ezid/var/www/download/public" folder on the server. We still need the "/apps/ezid/var/www/download/public" folder for other operation. But we don't need to provide public access over URL.

**Comment by jsjiang** [comment]
Update /ezid/etc/httpd/conf.d/03-ezid-nossl.conf to remove the following entries:
```
 	Alias /download /ezid/var/www/download/public
 	<Directory /ezid/var/www/download/public>
 		Require all granted
 		Options -Indexes
 		ErrorDocument 404 /download_error
 	</Directory>  
```

**Comment by ashleygould** [comment]
I have updated ansible configs to delete the `~/dowload` symlink and to omit `alias download` config in httpd configs.  see branch `disable_http_download`.  I have tagged this change as `3.2.9rc0`.  PR pending.

**Comment by ashleygould** [comment]
I reverted deleteion of `~/download` symlink and cut a new tag: 3.2.9rc1

**Comment by jsjiang** [comment]
* Tested 3.2.9rc1 on ezid-stg
* Merged branch to the develop branch then to the main branch
* created a tag v3.2.9 for prod deployment

**Comment by adambuttrick** [comment]
Released as part of https://github.com/CDLUC3/ezid/releases/tag/v3.2.9.
