### ISSUE TITLE
Deploy release v3.2.6 on EZID-PRD

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#584]
The release v3.2.6 contains following changes:
* remove Berkeley DB dependancies from EZID (#525, #473, #535)
* update BDB dependancies from puppet/ansible
* upgrade BootStrap and jQuery
* implement Matomo-API tracking

Deployment checklist:
- [x]  code reviewed
- [x] Unit, CI and integration tests performed
- [x] performance tests performed
- [x] UI tests performed
- [x] release candidate deployed and tested on ezid-stg

Deployment plan:
* Release candidate v3.2.6rc0 is on stage for testing (Friday 3/1 - )
* Production deployment is scheduled: Thursday 3/7

**Comment by jsjiang** [comment]
No Matomo, get metadata:

![Image](https://github.com/CDLUC3/ezid/assets/12803478/6f510c49-d5ca-4130-a7ca-a1a3a5e2b435)

With Matomo, get metadata:

![Image](https://github.com/CDLUC3/ezid/assets/12803478/97d8ae47-3789-45bc-8ee7-a4815d8edfcf)

**Comment by jsjiang** [comment]
Findings:
* total requests per second: lower with Matomo implementation 
* response times: higher with Matomo implementation

**Comment by sfisher** [comment]
It will be great to talk this over and see what we think.  I'll have to look over numbers more carefully.

**Comment by jsjiang** [comment]
> It will be great to talk this over and see what we think. I'll have to look over numbers more carefully.
Sounds good. We can perform some tests together tomorrow after OS patching is done.

**Comment by jsjiang** [comment]
* Performed another round of load tests on the "mint" API with and without matomo implementation. The performance is reduced about 15% with Matomo implementation. 
* The ezid team thinks the reduced 15% performance is acceptable and approved production implementation of Matomo this Thursday March 7.

Mint with 10 users with Matomo:

![Image](https://github.com/CDLUC3/ezid/assets/12803478/54334ca4-80e1-4329-901d-4e8f812fb9bb)

Mint with 10 users without Matomo;

![Image](https://github.com/CDLUC3/ezid/assets/12803478/76e87c58-28d3-4260-b269-d989ac93b004)

Compare reports (upper: with Matomo, lower: without Matomo)

![Image](https://github.com/CDLUC3/ezid/assets/12803478/1b8e1210-37a3-4663-8067-f94ffdf33e93)


![Image](https://github.com/CDLUC3/ezid/assets/12803478/530da402-80b7-420e-b640-df281bdeb390)
