### ISSUE TITLE
Submit create/update document to OpenSearch code

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#591]
Once we have a document, we need to be able to add documents to OpenSearch.

- [x] create code to create/update OpenSearch document record
- [x] create batch that updates all records (takes ~2 days to do all)

This code may be relatively easy, but there are a couple of different ways to do it--individual and batch mode (from background reading).  Perhaps we start with individual submission for one-off documents.

As a separate consideration we will also need a script to resend all data from the database to OpenSearch in that case, likely a batch update makes more sense.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19.
