### ISSUE TITLE
OpenSearch infrastructure for search

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#594]
I believe we will need to work with Ashley to get OpenSearch configured to use for dev/stg/prd environments.  During development I'm using a docker container to test basics, but this does not work past early development.

We will need to start discussions with Ashley, or perhaps there is something I can learn with limited access in the AWS management console as locked down by CDL?  (I haven't used it much since the dryad AWS console had fuller rights and was not locked down so much.)

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19.
