### ISSUE TITLE
Test OpenSearch with EZID's data scale

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#595]
The performance of OpenSearch may be different with the larger number of records in EZID (33 million?) vs a smaller test set for development.

I believe the stage server has more records for testing scale.  this ticket needs more fleshing out, but . . .

- Is search responsive
- How long does it take to regenerate search data using the scripts?
- Works as expected at scale?

**Comment by adambuttrick** [comment]
Fleshing out more complete criteria:

## Test Type
Performance and Functional

## Describe the functionality to be tested
We need to verify that OpenSearch is responsive and functions correctly when handling EZID's full record set.

## Describe the test scenario
1. Perform a series of search queries of varying complexity using the OpenSearch with the full record set:
   - [ ] Simple identifier lookup: 
     ```
     GET /id/{identifier}
     ```
   - [ ] Prefix matching search: 
     ```
     GET /id/{identifier_prefix}?prefix_match=yes
     ```
   - [ ] Search by creation date range: 
     ```
     createdAfter={start_date}&createdBefore={end_date}
     ```
   - [ ] Search by update date range: 
     ```
     updatedAfter={start_date}&updatedBefore={end_date}
     ```
   - [ ] Search by identifier type: 
     ```
     type={type1}&type={type2}
     ```
   - [ ] Search by identifier status: 
     ```
     status={status1}&status={status2}
     ```
   - [ ] Search by owner or ownergroup: 
     ```
     owner={username1}&owner={username2}
     ```
   - [ ] Search by metadata profile: 
     ```
     profile={profile1}&profile={profile2}
     ```
   - [ ] Complex query combining multiple parameters: 
     ```
     type={type}&status={status}&createdAfter={date}&profile={profile}
     ```
   - [ ] Search for exported/non-exported identifiers: 
     ```
     exported={yes_or_no}
     ```
   - [ ] Search for test or real identifiers: 
     ```
     permanence={test_or_real}
     ```
   - [ ] Search for Crossref or DataCite registered identifiers: 
     ```
     {crossref_or_datacite}={yes_or_no}
     ```

1. For each query:
   - [ ] Record response times
   - [ ] Compare response times to comparable searches in existing DB-based search, excluding known cases where query would degrade the service
   - [ ] Verify accuracy and completeness of results relative to the same DB-based search
   - [ ] Verify proper handling of pagination and large result sets
   - [ ] Test concurrency with multiple simultaneous searches

2. Conduct tests under load:
   - [ ] Simulate peak usage conditions (to the extent possible)
   - [ ] Monitor system resources
   - [ ] Verify stability with complex queries under high load

3. Test edge cases:
   - [ ] Queries returning very large result sets
   - [ ] Queries with no results
   - [ ] Malformed or invalid queries

## Expected outcome
- [ ] All search queries return results with expected/acceptable response times
- [ ] No significant degradation compared to DB-based search
- [ ] All search functionality works correctly with the full dataset
- [ ] Performance remains stable under load and with complex queries
- [ ] Search results are accurate and complete for all query types
- [ ] No unexpected behaviors or errors

**Comment by jsjiang** [comment]
@adambuttrick Hi Adam, The search parameters listed in test scenarios are for the batch download API. The parameters for the search request includes
* keywords
* identifier
* title
* creator
* publisher
* pubyear_from
* pubyear_to
* object_type
* id_type

Here is a sample query:
```
search?filtered=t&keywords=&identifier=doi%3A10.7270%2FQ2&title=&creator=&publisher=&pubyear_from=&pubyear_to=&object_type=&id_type=
```

There is no change to the batch download API.

**Comment by adambuttrick** [comment]
@jsjiang Thanks for catching this! I've revised. Let me know if all looks good.

**Comment by jsjiang** [comment]
Just added "Test keywords parameter" to the list.

**Comment by adambuttrick** [comment]
Requirement on https://github.com/CDLUC3/ezid/issues/653

**Comment by jsjiang** [comment]
Jing's test results:
* Aug 14, ezid-stg on commit `f79af50b8a7c996d8e541a5f8ddf05ba85d7c845`
 
Public search interface (without login)
* Keywords search:
  * keywords:(California Digital Library): returned 558 Search Results in 56 pages each with 10 entries;
    * page size change: changed to 50, 100 and worked OK
    * page navigation in page range: worked OK
    * page navigation out of page range:
      * <1: changed to 1 after a warning
      * > last page: changed to last page after warning
  * keywords:(California AND Digital AND Library): same results as above.
  * keywords:(California OR Digital OR Library): **got Page unavailable error**
  * keywords:(Awesome OR Cat): returned 6998 Search Results
* search identifier
  * identifier:(ark:/88122/sqwj0083): returned one record
  * identifier:(ark:/88122): returned 15194052 Search Results records; UI only shows the first 10K records.
    *  page navigation out of page range:
      * <1: changed to 1 after a warning
      * >  last page: **got Page unavailable error** 
* resourceTitle:(CAMEL Tobacco): returned 6629 records
* resourceCreator:(Reynolds): returned 1692244 Search Results
* resourcePublisher:(nature): returned 55 Search Results
* resourcePublicationYear:>=2020 AND resourcePublicationYear:<=2022: returned 388433 Search Results
* resourceType:(Journal): returned 22450 Search Results
* identifierType:(doi): returned 319044 Search Results
* identifierType:(ark): 23907595 Search Results
* identifierType:(ark) AND resourcePublicationYear:>=2020 AND resourcePublicationYear:<=2023: 331737 Search Results
* identifierType:(ark) AND resourceType:(Collection) AND resourcePublicationYear:>=2020 AND resourcePublicationYear:<=2023: 5547 Search Results
* identifierType:(ark) AND resourceCreator:(Evers) AND resourceType:(Collection) AND resourcePublicationYear:>=2020 AND resourcePublicationYear:<=202: 100 results
* identifierType:(ark) AND resourceTitle:(body) AND resourceCreator:(Evers) AND resourceType:(Collection) AND resourcePublicationYear:>=2020 AND resourcePublicationYear:<=2023: 11 results
* keywords:(California) AND identifierType:(ark) AND resourcePublicationYear:>=2020 AND resourcePublicationYear:<=2023: 1690 search results
* Customize view: worked OK

**Comment by jsjiang** [comment]
Jing's test results:

Aug 15, ezid-stg on commit f79af50b8a7c996d8e541a5f8ddf05ba85d7c845
Public search interface (with login as apitest):

* Mange IDS page: returned 98 Identifiers
* Download all: created downloadable file `S0VxH9CbVcEOZAuq.zip`. This file contains 166 identifiers. 
**Note: The number of identifiers in the report does not match to what shows in the `Manage IDs` page (166 vs 98)**
* **View identifier got `No such identifier:  doi:10.31223/FK3TEST_1.` error.**
Note: test identifiers are deleted regularly from the `Search Identifier` table through the Delete action of the `SearchIndexerQueue`

**Comment by jsjiang** [comment]
Here is the full list of identifiers that showed in the download all report but not on the UI for apitest account:

1. ark:/99999/fk4184tn6s
2. ark:/99999/fk4281vj6w
3. ark:/99999/fk43b7kv04
4. ark:/99999/fk43j50m34
5. ark:/99999/fk4515jf90
6. ark:/99999/fk4612kc1f
7. ark:/99999/fk4795qd8z
8. ark:/99999/fk48s6883p
9. ark:/99999/fk49s39549
10. ark:/99999/fk4c26f73h
11. ark:/99999/fk4dj7029f
12. ark:/99999/fk4fj40z93
13. ark:/99999/fk4fn2qb94
14. ark:/99999/fk4j97pw5n
15. ark:/99999/fk4k94qs26
16. ark:/99999/fk4kd3f535
17. ark:/99999/fk4n31cs6z
18. ark:/99999/fk4p28dp8v
19. ark:/99999/fk4pz6r64j
20. ark:/99999/fk4q544z8z
21. ark:/99999/fk4rv23m15
22. ark:/99999/fk4sr0f39x
23. ark:/99999/fk4tx4vs69
24. ark:/99999/fk4wh4412b
25. ark:/99999/fk4zp5kk9h
26. doi:10.15697/FK2107G
27. doi:10.15697/FK2207T 
28. doi:10.15697/FK24P9X
29. doi:10.15697/FK25Q0X
30. doi:10.15697/FK28H2H
31. doi:10.15697/FK29H2V
32. doi:10.15697/FK2D65Q
33. doi:10.15697/FK2F652
34. doi:10.15697/FK2J07N
35. doi:10.15697/FK2K06K
36. doi:10.15697/FK2NQ0R
37. doi:10.15697/FK2PQ03
38. doi:10.15697/FK2RH2B
39. doi:10.15697/FK2SH33
40. doi:10.15697/FK2W948
41. doi:10.15697/FK2X65W
42. doi:10.5072/FK2086D79C
43. doi:10.5072/FK2154QR91
44. doi:10.5072/FK21G0TX60
45. doi:10.5072/FK2320355K
46. doi:10.5072/FK23R10W7G1
47. doi:10.5072/FK23X8DP3M
48. doi:10.5072/FK24X5FK26
49. doi:10.5072/FK2571JR1J
50. doi:10.5072/FK26Q23K6Z
51. doi:10.5072/FK27P94G7B
52. doi:10.5072/FK29028J58
53. doi:10.5072/FK2BG2TD13
54. doi:10.5072/FK2G73J649
55. doi:10.5072/FK2H70K33W
56. doi:10.5072/FK2KH0R22V
57. doi:10.5072/FK2M04809J
58. doi:10.5072/FK2N018W96
59. doi:10.5072/FK2N87D27W
60. doi:10.5072/FK2Q52RG43
61. doi:10.5072/FK2QR4ZT3C
62. doi:10.5072/FK2RR20Q1V
63. doi:10.5072/FK2S183W1G
64. doi:10.5072/FK2V69KF5J
65. doi:10.5072/FK2VH5PM6K
66. doi:10.5072/FK2WH2QH6P
67. doi:10.5072/FK2WS8TP4X
68. doi:10.5072/FK2Z89CJ11

**Comment by adambuttrick** [comment]
Could we also login to the stage as admin and test with some of the data in the user account view to verify?

**Comment by jsjiang** [comment]
Testing UI with login `merritt`:
* Manage IDs page: 3,116,205
* Download all: https://ezid-stg.cdlib.org/s3_download/B7XxQFxqXe6ElG45.zip
  * It took a long time for EZID to generate this file
* RDS: select count from `ezidapp_identifier` and `ezidapp_searchidentifier` for `merritt` (owner_id=124) all returned 3,116,205

**Comment by jsjiang** [comment]
Checked records counts on 8/16: 

Stage:
* records count in the `ezidapp_identifier` table for owner=2:  92.
* record counts in the `ezidapp_searchidentifier` table for owner=2: 158

Performed the same queries on PRD, the records counts in the  `ezidapp_identifier` and  `ezidapp_searchidentifier`  tables are the same  for owner=2 (apitest) and owner=124 (merritt):
```
# 4084152
select count(id) from ezidapp_identifier where owner_id = 124 ;
# 4084152
select count(id) from ezidapp_searchidentifier where owner_id = 124;
# 1860
select count(id) from ezidapp_identifier where owner_id = 2 ;
# 1860
select count(id) from ezidapp_searchidentifier where owner_id = 2;
```

So the differences on stage is caused by inconsistent data in the stage environment.

**Comment by jsjiang** [comment]
Jing retested following items 8/23 on ezid-stg with commit `ed6641b76b12c413e2520f650dfe1d7a8df8b885`:
* keywords:(California OR Digital OR Library): returned 1222514 results without error - this is expected
* Out of page range navigation: show warning, then direct to the first or last page - this is expected.

**Comment by adambuttrick** [comment]
Tests passed as part of release https://github.com/CDLUC3/ezid/releases/tag/v3.2.19
