### ISSUE TITLE
API search functionality to OpenSearch

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#603]
I believe there is an API call that searches by keyword from what Jing mentioned.

I looked through the code and I do not see anything like this, perhaps the batch download action is what is being referred to?

I see reference to a curl command like

```
curl -u username:password -d format=anvl -d type=ark -d type=doi -d permanence=real https://ezid.cdlib.org/download_request
```

I tested this with apitest, but I don't currently have all the 30m records populated and I'm not sure there are any records yet (probably at the end of the index).  I need to check with @jsjiang to see if we have other logins I can test or maybe wait for indexing to finish.

**Comment by jsjiang** [comment]
@sfisher Hi Scott,  the batch download request is processed by an asynchronous background job `ezidapp/management/commands/proc-download.py`. In the` _harvest1` function it searches the `searchIndetifier` table. [Here is the code in the main branch](https://github.com/CDLUC3/ezid/blob/13252f96d7d757d675a2230b8ecc5c9b37a79cbb/ezidapp/management/commands/proc-download.py#L284-L295).

Jing

**Comment by adambuttrick** [comment]
Was determined to be out of scope for initial OpenSearch release. Will need to revisit implementation in OpenSearch as a separate issue, if needed.
