### ISSUE TITLE
Design OpenSearch index for EZID search functionalities

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#606]
Design OpenSearch index for EZID search functionalities. [Document](https://docs.google.com/document/d/1RKWJ6Ve4Z3C5IQns0y71lzG6PcHIp1bUQ2NnaOEAJMA/edit#heading=h.5r68ud10e6w9):
* search requirements
* index design

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19
