### ISSUE TITLE
Update UCB library email addresses

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#614]
The UC Berkeley Library is retiring their @library.berkeley.edu emails by end of the calendar year. Email addresses with "account@library.berkeley.edu" format will be changed to: "account@berkeley.edu". Update EZID to reflects this change:

- [x] Find affected email addressed
- [x] Contact users to confirm new email addresses
- [x] Update email addressed in EZID

**Comment by jsjiang** [comment]
```
select username, displayname, accountemail
, primaryContactName, primaryContactEmail
, secondaryContactName, secondaryContactEmail
from ezidapp_user 
where accountEmail like '%library.berkeley%'
or primaryContactEmail like '%library.berkeley%'
or secondaryContactEmail like '%library.berkeley%';
```

|- username	|displayname	|accountemail	|primaryContactName	|primaryContactEmail	|secondaryContactName	|secondaryContactEmail -|
| ---------	| ----------	| ---------	| -------------------	| ---------	| ------------	| -----|
|ucb-genx	|for use by GenX to mint EAD ARKs	|tparks@library.berkeley.edu	|Todd Parks	|tparks@library.berkeley.edu	| | |
|ucb-its	|Institute of Transportation Studies, UC Berkeley	|itslib@berkeley.edu	|Kendra K. Levine	|kklevine@berkeley.edu	|Rita Evans	|revans@library.berkeley.edu|
|ucb-gis	|UCB Library Systems Office	|apollock@library.berkeley.edu	|Alvin Pollock	|apollock@library.berkeley.edu	|Lynne Grigsby	|lgrigsby@library.berkeley.edu|

**Comment by adambuttrick** [comment]
Updated all addresses to the `berkeley.edu` forms where staff were still listed in the directory. Where they were not, changed the secondary contact to be the primary with `berkeley.edu` email. Only outstanding issue is with the `ucb-genx` account, for which there is no secondary account. Following up with UCB to inquire how to resolve.

**Comment by adambuttrick** [comment]
All contacts have been corrected or updated with `berkeley.edu` emails/
