### ISSUE TITLE
Make initial character match field for identifier search

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#619]
EZID allows non-exact identifier "startswith" type match (ie identifier LIKE "ark:/123.456/kk%" in SQL).

OpenSearch allows implementation of this with a special "keyword" format field and a "prefix" query.  They warn that "search.allow_expensive_queries" has to be enabled for this to work and

"It's important to note that prefix queries can be resource-intensive and can lead to performance issues.They are not recommended for large scale text searching. For better performance, consider using an edge n-gram tokenizer at index time or a completion suggester for auto-complete functionality."

It seems like moving this functionality over to OpenSearch will just help to replicate some of the existing performance issues along with it . . . but that seems like what we're doing and not looking at changing functionality at the moment until Adam starts.

- [x] Figure out how to customize the OpenSearch schema datatypes for this field (or all fields i I have to) rather than using the default.
- [x] Put identifier that is searched this way to a separate field with keyword type.
- [x] Implement match as `prefix` query instead of term query.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19
