### ISSUE TITLE
Base "manage ids" display from opensearch

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#622]
Should be able to display table of items from OpenSeach that appears the same as from DB.

- [x] basic query works
- [x] results display in table

---

I was pleasantly surprised to find out that my changes to the util libraries successfully got  the "manage" page working!  I thought I'd have to do much more, but I'm looking into the functionality to determine where there are issues remaining compared to the current functionality.

- [x] "ID Status" is displaying as a character code rather than a user-friendly status phrase.
- [x] "ID Status" does not sort correctly (the rest of the fields seem to)

It looks to me like other stuff works, but I need to go through and test every field in the advanced search for manage IDs.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19.
