### ISSUE TITLE
Advanced search form brings up correct results from OpenSearch

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#623]
ensure each of these form fields filters appropriately, verify correct results.

- [x] General words
- [x] Identifier
- [x] Identifier prefix
- [x] Title
- [x] Creator
- [x] Publisher
- [x] Publication year and range
- [x] ~"object type" (book, dataset, etc)~
- [x] Type of identifier (ark/doi)

I wasn't able to verify "object type" but I only currently have a subset of data in the index and it doesn't seem like it's set in OpenSearch.  IDK if it's because something is wrong or it's not commonly set.  It took me a while to find a "publisher" that worked, but searching for "California" seems to work.

**Comment by sfisher** [comment]
This all works except searching for the resource type, which it seems like doesn't so I'll create a bug ticket for that.

It is hard to test without the full index which takes days to re-index, so the best way to to index some things manually with that attribute and be sure they're in for testing.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19.
