### ISSUE TITLE
Create new shoulders for eScholarship

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#624]
From Charlotte:
Hi EZID team, we have two journals that need DOI shoulders in row 27 and 28 of [this spreadsheet: ](https://docs.google.com/spreadsheets/d/1BP-_clMt5QL5QHJLmHzyeTNHlAsizXGI6vPZq4FReWc/edit?pli=1#gid=0)

**Comment by jsjiang** [comment]
Ref ticekt: #608

**Comment by jsjiang** [comment]
* Undergraduate Research Journal of Psychology at UCLA: 10.5070/JP2
* MELA Notes: 10.5070/M7

**Comment by jsjiang** [comment]
On ezid-stg:
```
ezid@uc3-ezidui-stg01:15:58:19:~/ezid$ python manage.py shoulder-create-doi doi:10.5070/JP2 "Undergraduate Research Journal of Psychology at UCLA" --crossref
ezidapp.management.commands.shoulder-create-doi INFO     shoulder-create-doi - Shoulder created
ezid@uc3-ezidui-stg01:15:58:36:~/ezid$ python manage.py shoulder-create-doi doi:10.5070/M7 "MELA Notes" --crossref
ezidapp.management.commands.shoulder-create-doi INFO     shoulder-create-doi - Shoulder created
```

**Comment by jsjiang** [comment]
Grant shoulder access to user accounts in ezid-stg UI 
* Logon to ezid-stg.cdlib.org as the admin user
* go to ezid-stg.cdlib.org/admin
* go to "Groups"
* find the `eschol_harvester` group
* add both `doi:10.5070/JP2` and `doi:10.5070/M7` to the allowed shoulder list
* find the `ucla-library` group and add `doi:10.5070/JP2` to the allowed shoulder list
* find the `ucsdlib` group and add `doi:10.5070/M7` to the allowed shoulder list
* Go to the "Users"
* find the `ucla-eschol` account and add `doi:10.5070/JP2` to the allowed shoulder list
* find the `ucsd-eschol` account and add `doi:10.5070/M7` to the allowed shoulder list

**Comment by jsjiang** [comment]
To do: create shoulders on EZID-PRD

**Comment by adambuttrick** [comment]
Created shoulders on EZID-PRD and assigned to appropriate groups and accounts.
