### ISSUE TITLE
Advanced "manage IDs" returns appropriate results from form

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#626]
Be sure "manage IDs" works with all the advanced functionality (more than is in search):

- [x] full text search
- [x] View identifiers owned by
- [x] identifier
- [x] identifier prefix
- [x] title
- [x] creator
- [x] publisher
- [x] publication year and range
- [x] object type (dataset/book/etc)
- [x] ID create date (date range)
- [x] ID update date (date range)
- [x] ID status (public/reserved/unavailable)
- [x] Allows harvesting?
- [x] Has metadata?

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19.
