### ISSUE TITLE
Setup Adam's account in EZID

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#628]
Setup Adam's accounts:

- [x] Account and access to the EZID EC2 instances
- [x] Add to GitHub EZID group
- [x] Add to LastPass group
- [x] Account in EZID app

Setup Adam's account in EZID: One option is to re-use Maria's account so Adam gets all the privileges including "Realm Administrator" who get link check reports through BCC:

Jing noted April 10:

We got lots of bounced "monthly EZID link check report" emails due to rejected email address (Maria's email). I checked the code and found the email address was retrieved from the user accounts with the "isRealmAdministrator=True". Apparently, Maria is the only user with this flag set to true. The link check reports are BCC'ed to the Realm Administrators. I haven't figured out how to setup/unset this "isRealmAdministrator" flag in the UI.

**Comment by adambuttrick** [comment]
I created my own account, set myself as the realm administrator, and removed this flag from Maria's. All other access is provisioned, so this is now complete.
