### ISSUE TITLE
Manage IDs: group filter works, but account filter does not

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#634]
Example to see this bug: go to the Manage page.

Select something such as `[UCI] group: UC Irvine Libraries`  You will see results from a few different owners (such as `uci-exonerate`).  However, when you select just that owner ('uci-exonerate') from the list it now returns 0 results even though the owner exists.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19.
