### ISSUE TITLE
Create a new shoulder for Réseau Canopé

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#638]
Réseau Canopé has requested a new shoulder

Institution: Réseau Canopé
Type of identifier: ARK
Prefix/NAAN: 19153
Shoulder value: spdc9
Shoulder name: Scolomfr -- Fovéa

**Comment by jsjiang** [comment]
User name: admin-canope
Group name: admin-canope

Instructions:
* [how to create a shoulder](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/how_to_create_shoulders.md)
* [how to grant shoulder access to groups and users](https://github.com/CDLUC3/ezid-docs-internal/blob/main/docs/how_to_grant_access_to_shoulders.md)

**Comment by jsjiang** [comment]
Created shoulder `ark:/19153/spdc9` on stage and prod
```
python manage.py shoulder-create-ark ark:/19153/spdc9 "Scolomfr -- Fovéa"
```
