### ISSUE TITLE
[BUG] Inconsistent ARK creation/update behavior when using DataCite schema 4.5 with "Instrument" resource type

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#639]
**Describe the bug**

Duke University is reporting that ARK creation/update via the API is successful using DataCite schema 4.5, with the `resourceTypeGeneral` set to "Instrument" and the `Status` is set to "reserved." However, with `resourceTypeGeneral` set to "Instrument" and the `Status` is set to "public", the ARK creation/update fails.

**To Reproduce**

1\. Create an ARK using the DataCite schema 4.5

2\. Set `resourceTypeGeneral` to "Instrument"

3\. Set `Status` to "reserved"

4\. Create/update ARK (successful)

5\. Change `Status` to "public"

6\. Create/update ARK (fails)

**Expected behavior**

It is unclear whether the EZID API fully supports DataCite schema 4.5 for ARK metadata, specifically when using the new resource type "Instrument," or if this is a result of an issue with the change of status. If this is not dependent on the schema upgrade, the ARK creation/update should be successful regardless of the `Status` value when using DataCite schema 4.5 with `resourceTypeGeneral` set to "Instrument."

**Comment by adambuttrick** [comment]
Example from the original ticket:

Request:
"_status: public\n_target: [https://www.morphosource.org/concern/devices/000200409\n_profile](https://www.morphosource.org/concern/devices/000200409/n_profile): datacite\ndatacite: <?xml version=\"1.0\" encoding=\"UTF-8\"?><resource xmlns:xsi=\[http://www.w3.org/2001/XMLSchema-instance\](http://www.w3.org/2001/XMLSchema-instance/) xmlns=\[http://datacite.org/schema/kernel-4\](http://datacite.org/schema/kernel-4/) xsi:schemaLocation=\[http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.5/metadata.xsd\](http://datacite.org/schema/kernel-4%20http:/schema.datacite.org/meta/kernel-4.5/metadata.xsd/)><identifier identifierType=\"ARK\"></identifier><creators><creator><creatorName>Choy, Simon</creatorName></creator></creators><titles><title>device local B13</title></titles><publisher>MorphoSource.org</publisher><publicationYear>2024</publicationYear><resourceType resourceTypeGeneral=\"Instrument\"></resourceType><descriptions><description descriptionType=\"Abstract\"></description></descriptions></resource>%0A"

Response:
error: bad request - error="ValidationError({'datacite': ['Metadata validation error: DocumentInvalid("Element \'{[http://datacite.org/schema/kernel-4}resourceType\](http://datacite.org/schema/kernel-4%7DresourceType/)', attribute \'resourceTypeGeneral\': [facet \'enumeration\'] The value \'Instrument\' is not an element of the set {\'Audiovisual\', \'Book\', \'BookChapter\', \'Collection\', \'ComputationalNotebook\', \'ConferencePaper\', \'ConferenceProceeding\', \'DataPaper\', \'Dataset\', \'Dissertation\', \'Event\', \'Image\', \'InteractiveResource\', \'Journal\', \'JournalArticle\', \'Model\', \'OutputManagementPlan\', \'PeerReview\', \'PhysicalObject\', \'Preprint\', \'Report\', \'Service\', \'Software\', \'Sound\', \'Standard\', \'Text\', \'Workflow\', \'Other\'}., line 1"). metadata="<?xml version="1.0" encoding="UTF-8"?><resource xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xmlns=http://datacite.org/schema/kernel-4 xsi:schemaLocation=[http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.5/metadata.xsd](http://datacite.org/schema/kernel-4%20http:/schema.datacite.org/meta/kernel-4.5/metadata.xsd)><identifier identifierType="ARK"></identifier><creators><creator><creatorName>Choy, Simon</creatorName></creator></creators><titles><title>device local B13</title></titles><publisher>MorphoSource.org</publisher><publicationYear>2024</publicationYear><resourceType resourceTypeGeneral="Instrument"></resourceType><descriptions><description descriptionType="Abstract"></description></descriptions></resource>"']})" Metadata: {'datacite': '<?xml version="1.0" encoding="UTF-8"?><resource '              'xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance '              'xmlns=http://datacite.org/schema/kernel-4 '              'xsi:schemaLocation=http://datacite.org/schema/kernel-4 '              'http://schema.datacite.org/meta/kernel-4.5/metadata.xsd><identifier '              'identifierType="ARK"></identifier><creators><creator><creatorName>Choy, '              'Simon</creatorName></creator></creators><titles><title>device '              'local '              'B13</title></titles><publisher>MorphoSource.org</publisher><publicationYear>2024</publicationYear><resourceType '              'resourceTypeGeneral="Instrument"></resourceType><descriptions><description '              'descriptionType="Abstract"></description></descriptions></resource>'}

Requesting a few others.

**Comment by adambuttrick** [comment]
Confirmed use of reserved status. Additional ARKs all appear to have been registered in the test account, so these may have been wiped. I checked in the admin and couldn't find, nor were they to be found in report when I dumped all of apitest:

ark:/99999/fk4/200407
ark:/99999/fk4/200406
ark:/99999/fk4/200379

I've asked for the metadata.

**Comment by jsjiang** [comment]
EZID workflow (without DataCite 4.5 support):
* when the metadata is passed in the "datacite: xml document" format:
  * if status="reserved", the xml document is not validated against the DataCite schema - this is why they were able to create/update "reserved" records.
  * when status!="reserved", the xml document is validated against the DataCite schema - this is why creating status=public records with DataCite 4.5 supported resourcetypeGeneral="instrument" failed.

In case they use the "datacite.fieldname: value" format:
  * the "resourcetypeGeneral" is supported by using the "datacite.resourcetype: general type/specific type" format. The provided "general type" will be validated against the DataCite schema defined terms. 
  * if "datacite.resourcetypeGeneral: value" data element is provided in the metadata, EZID will keep the data field as is without validation.

**Comment by jsjiang** [comment]
EZID DataCite 4.5 support will not change above workflow.

**Comment by adambuttrick** [comment]
Reported back to user.
