### ISSUE TITLE
Resolve dependabot alerts in poetry.lock

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#658]
Here is a note for the alert on upgrading `urllib3`. Refer to a [newer note for a full list of alerts](https://github.com/CDLUC3/ezid/issues/658#issuecomment-2223970492) that need to be resolved.

Dependabot recommends to upgrade `urllib3` from 1.26.18 to 1.26.19. There are two `urllib3` packages in the `poetry.lock` file, one for Python 3.8+ and one for earlier versions (">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"). However Dependabot created pull request only kept one `urllib3` for Python earlier Python versions (">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"). 

Find a way to upgrade `urllib3` to the proper version.

Current `poetry.loc`:
```
[[package]]
name = "urllib3"
version = "1.26.18"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"
files = [
    {file = "urllib3-1.26.18-py2.py3-none-any.whl", hash = "sha256:34b97092d7e0a3a8cf7cd10e386f401b3737364026c45e622aa02903dffe0f07"},
    {file = "urllib3-1.26.18.tar.gz", hash = "sha256:f8ecc1bba5667413457c529ab955bf8c67b45db799d159066261719e328580a0"},
]

[package.extras]
brotli = ["brotli (==1.0.9)", "brotli (>=1.0.9)", "brotlicffi (>=0.8.0)", "brotlipy (>=0.6.0)"]
secure = ["certifi", "cryptography (>=1.3.4)", "idna (>=2.0.0)", "ipaddress", "pyOpenSSL (>=0.14)", "urllib3-secure-extra"]
socks = ["PySocks (>=1.5.6,!=1.5.7,<2.0)"]

[[package]]
name = "urllib3"
version = "2.2.1"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = ">=3.8"
files = [
    {file = "urllib3-2.2.1-py3-none-any.whl", hash = "sha256:450b20ec296a467077128bff42b73080516e71b56ff59a60a02bef2232c4fa9d"},
    {file = "urllib3-2.2.1.tar.gz", hash = "sha256:d0570876c61ab9e520d776c38acbbb5b05a776d3f9ff98a5c8fd5162a444cf19"},
]

[package.extras]
brotli = ["brotli (>=1.0.9)", "brotlicffi (>=0.8.0)"]
h2 = ["h2 (>=4,<5)"]
socks = ["pysocks (>=1.5.6,!=1.5.7,<2.0)"]
zstd = ["zstandard (>=0.18.0)"]
```

Dependabot changes:

From:
```
[[package]]
name = "urllib3"
version = "1.26.18"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"
files = [
    {file = "urllib3-1.26.18-py2.py3-none-any.whl", hash = "sha256:34b97092d7e0a3a8cf7cd10e386f401b3737364026c45e622aa02903dffe0f07"},
    {file = "urllib3-1.26.18.tar.gz", hash = "sha256:f8ecc1bba5667413457c529ab955bf8c67b45db799d159066261719e328580a0"},
]
```
To:
```
[[package]]
name = "urllib3"
version = "1.26.19"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,>=2.7"
files = [
    {file = "urllib3-1.26.19-py2.py3-none-any.whl", hash = "sha256:37a0344459b199fce0e80b0d3569837ec6b6937435c5244e7fd73fa6006830f3"},
    {file = "urllib3-1.26.19.tar.gz", hash = "sha256:3e3d753a8618b86d7de333b4223005f68720bcd6a7d2bcb9fbd2229ec7c1e429"},
]
```

Removed:
```
[[package]]
name = "urllib3"
version = "2.2.1"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = ">=3.8"
files = [
    {file = "urllib3-2.2.1-py3-none-any.whl", hash = "sha256:450b20ec296a467077128bff42b73080516e71b56ff59a60a02bef2232c4fa9d"},
    {file = "urllib3-2.2.1.tar.gz", hash = "sha256:d0570876c61ab9e520d776c38acbbb5b05a776d3f9ff98a5c8fd5162a444cf19"},
]

[package.extras]
brotli = ["brotli (>=1.0.9)", "brotlicffi (>=0.8.0)"]
h2 = ["h2 (>=4,<5)"]
socks = ["pysocks (>=1.5.6,!=1.5.7,<2.0)"]
zstd = ["zstandard (>=0.18.0)"]
```

**Comment by jsjiang** [comment]
Manually updating Python package dependancies by running the `poetry add ${package}@latest` command didn't update the `urllib3` versions in `poetry.lock` file. The command showed that:
* mysqlclient requires urllib3 version 2.2.1  
* mysql requires urllib3 version 1.26.18
* there are no changes to the `urllib3` package entries in the `poetry.lock` file

Output from running the `update_project.sh` script:
```
Package operations: 0 installs, 4 updates, 0 removals

  - Updating urllib3 (1.26.18 -> 2.2.1)
  - Downgrading boto3 (1.34.130 -> 1.34.119)
  - Downgrading filelock (3.15.3 -> 3.14.0)
  - Downgrading sqlalchemy (2.0.31 -> 2.0.30)
Using version ^2.2.4 for mysqlclient
...

Package operations: 0 installs, 3 updates, 0 removals

  - Downgrading urllib3 (2.2.1 -> 1.26.18)
  - Updating botocore (1.34.130 -> 1.34.131)
  - Updating boto3 (1.34.119 -> 1.34.131)

Writing lock file
Using version ^0.0.3 for mysql
```

`urllib3` packages in `poetry.lock`:
```
[[package]]
name = "urllib3"
version = "1.26.18"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"
files = [
    {file = "urllib3-1.26.18-py2.py3-none-any.whl", hash = "sha256:34b97092d7e0a3a8cf7cd10e386f401b3737364026c45e622aa02903dffe0f07"},
    {file = "urllib3-1.26.18.tar.gz", hash = "sha256:f8ecc1bba5667413457c529ab955bf8c67b45db799d159066261719e328580a0"},
]

[package.extras]
brotli = ["brotli (==1.0.9)", "brotli (>=1.0.9)", "brotlicffi (>=0.8.0)", "brotlipy (>=0.6.0)"]
secure = ["certifi", "cryptography (>=1.3.4)", "idna (>=2.0.0)", "ipaddress", "pyOpenSSL (>=0.14)", "urllib3-secure-extra"]
socks = ["PySocks (>=1.5.6,!=1.5.7,<2.0)"]

[[package]]
name = "urllib3"
version = "2.2.1"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = ">=3.8"
files = [
    {file = "urllib3-2.2.1-py3-none-any.whl", hash = "sha256:450b20ec296a467077128bff42b73080516e71b56ff59a60a02bef2232c4fa9d"},
    {file = "urllib3-2.2.1.tar.gz", hash = "sha256:d0570876c61ab9e520d776c38acbbb5b05a776d3f9ff98a5c8fd5162a444cf19"},
]

[package.extras]
brotli = ["brotli (>=1.0.9)", "brotlicffi (>=0.8.0)"]
h2 = ["h2 (>=4,<5)"]
socks = ["pysocks (>=1.5.6,!=1.5.7,<2.0)"]
zstd = ["zstandard (>=0.18.0)"]
```

Conclusion:
* mysqlclient and mysql requires different versions of urllib3
* mysqlclient and mysql are still not supporting the latest urllib3 releases for version 1 (1.26.19) & version 2 (2.2.2)
* Since the Dependabot alert Severity is relatively low (4.4/10), we could dismiss this alert now. Hopefully the urllib3 library will get updated with mysqlclient and mysql updates in the near future.

**Comment by adambuttrick** [comment]
From the Python Package Index description, [mysql](https://pypi.org/project/mysql/) appears to be a virtual/placeholder package for [MySQL-python](https://pypi.org/project/MySQL-python/) (Python 2) or [mysqlclient](https://pypi.org/project/mysqlclient/) (Python 3) 


I'm guessing for us this now equates to mysqlclient, since we upgraded to Python 3. This also corresponds to the package.extras section of our poetry.lock file:

https://github.com/CDLUC3/ezid/blob/7530b73534b7aca5831ab393e16c913a1be1d294/poetry.lock#L1293


It's not clear to me, however, why this is pulling in this old version of urlib3, as downloading the [tar file](https://pypi.org/project/mysql/#files) for this just lists mysqlclient in the requires.txt file. Likewise, the Github project does not have this as an explicit dependency and none of its requirements seem to either:

https://github.com/PyMySQL/mysqlclient/blob/main/requirements.txt


Setting all that aside, what this may mean is that imports that use mysql in ezid may just function as a simple alias import to the mysqlclient library, e.g. in these places:

https://github.com/CDLUC3/ezid/blob/7530b73534b7aca5831ab393e16c913a1be1d294/migrate_db_to_py3/db-update-fk.py#L19

https://github.com/CDLUC3/ezid/blob/7530b73534b7aca5831ab393e16c913a1be1d294/migrate_db_to_py3/run-migration.py#L16

https://github.com/CDLUC3/ezid/blob/7530b73534b7aca5831ab393e16c913a1be1d294/migrate_db_to_py3/db-migrate-blobs-to-metadata.py#L25

https://github.com/CDLUC3/ezid/blob/7530b73534b7aca5831ab393e16c913a1be1d294/migrate_db_to_py3/db-migrate-blobs-to-metadata.py#L25

In which case, we could look at updating to make these explicitly reference mysqlclient, remove the virtual package from the Python packaging, and see if that resolves the conflicting dependency.

However, since this is just my guesswork and the above is pretty core DB logic, I'll leave this to our brilliant technical lead to further investigate!

**Comment by jsjiang** [comment]
Good points. Scripts in the `ezid/migrate_db_to_py3` were developed for Python 3 upgrade. We can either replace `mysql` with `mysqlclient` or remove these scripts.

**Comment by jsjiang** [comment]
MySQL related packages:
* pymysql - Pure Python MySQL driver
* mysql - Virtual package for MySQL-python; package.dependencie: mysqlclient
* mysqlclient - Python interface to MySQL
* aiomysql - MySQL driver for asyncio; package.dependencie: PyMySQL

**Comment by jsjiang** [comment]
* The urllib3 package is required by the `botocore` and `requests` packages. It is not a dependency for the sql related packages. The output from the `update_project.sh` script was miss leading.
* Running the `update_project.sh` script which calls the `poetry add package_name@latest` command for each package updated packages listed in `pyproject.toml` to the latest versions. However the package versions for sub-dependency `urllib3` was not changed in `poetry.lock`
* Running the `poetry update` command only with out running the `update_project.sh` script only updated `poetry.lock` but not the `pyproject.toml` file

It looks like we need to run both the `poetry add package_name@latest` and `poetry update  package_name` commands in sequence:
1. run the `update_project.sh` script to update each package to the latest version
2. run the `poetry update` command to update all dependencies to their latest compatible versions

diff `poetry.lock`:
```
 [[package]]
 name = "urllib3"
-version = "1.26.18"
+version = "1.26.19"

[[package]]
 name = "urllib3"
-version = "2.2.1"
+version = "2.2.2"
```

**Comment by adambuttrick** [comment]
Part of #663.

**Comment by jsjiang** [comment]
A few more Dependabot alters in [poetry.lock](https://github.com/CDLUC3/ezid/blob/-/poetry.lock)
* Django vulnerable to Denial of Service #141 - High (requires Django 4.2.14)
* Django Path Traversal vulnerability #139 - High (requires Django 4.2.14)
* Django vulnerable to Denial of Service #138 - high (requires Django 4.2.14)
* Django vulnerable to user enumeration attack #140 - moderate (requires Django 4.2.14)
* jrburke requirejs vulnerable to prototype pollution #137 - high (no Patched version)
* urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects #135 - Moderate (requires urllib3 v1.26.19)
* urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects #133 - Moderate (requires urllib3 v2.2.2)
* Certifi removes GLOBALTRUST root certificate #136

**Comment by jsjiang** [comment]
Procedure:
* run the `update_pyproject.sh` script to upgrade packages (all but not Python and Django) and dependencies 
* run the `poetry add django@^4.2.14` to upgrade Django to version 4.2.14

**Comment by jsjiang** [comment]
Package version changesi `pyproject.toml`:
```
-- django = "^4.2.11"
++ django = "^4.2.14"

-- boto3 = "^1.34.119"
++ boto3 = "^1.34.143"

-- filelock = "^3.14.0"
++ filelock = "^3.15.4"

-- ecs-logging = "^2.1.0"
++ ecs-logging = "^2.2.0"

-- sqlalchemy = "^2.0.30"
++ sqlalchemy = "^2.0.31"
```

Dependencies changes in `poetry.lock`:
```
[[package]]
name = "boto3"
-- version = "1.34.119"
++ version = "1.34.143"

[package.dependencies]
-- botocore = ">=1.34.119,<1.35.0"
++ botocore = ">=1.34.143,<1.35.0"

[[package]]
name = "botocore"
-- version = "1.34.119"
++ version = "1.34.143"

[[package]]
name = "certifi"
-- version = "2024.6.2"
++ version = "2024.7.4"

[[package]]
name = "django"
-- version = "4.2.13"
++ version = "4.2.14"

[[package]]
name = "ecs-logging"
-- version = "2.1.0"
++ version = "2.2.0"

[[package]]
name = "filelock"
-- version = "3.14.0"
++ version = "3.15.4"

[[package]]
name = "prompt-toolkit"
-- version = "3.0.46"
++ version = "3.0.47"

[[package]]
name = "s3transfer"
-- version = "0.10.1"
++ version = "0.10.2"

[[package]]
name = "sqlalchemy"
-- version = "2.0.30"
++ version = "2.0.31"

name = "typing-extensions"
-- version = "4.12.1"
++ version = "4.12.2"

[[package]]
name = "urllib3"
-- version = "1.26.18"
++ version = "1.26.19"

[[package]]
name = "urllib3"
-- version = "2.2.1"
++ version = "2.2.2"
```

**Comment by jsjiang** [comment]
Django release notes: 
* 4.2.12: https://docs.djangoproject.com/en/5.0/releases/4.2.12/
* 4.2.13: https://docs.djangoproject.com/en/5.0/releases/4.2.13/
* 4.2.14: https://docs.djangoproject.com/en/5.0/releases/4.2.14/

**Comment by jsjiang** [comment]
* Changes were applied to EZID-PRD on July 16 with release v3.2.15
* Dependabot alerts were automatically resolved after the code change.
