### ISSUE TITLE
Verify Crossref to DataCite schema convertor is DataCite 4.5 compatible

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#674]
EZID has a function `crossrefToDatacite` to convert a Crossref Deposit Schema <http://help.crossref.org/deposit_schema> document to DataCite. The `crossref2datacite.xsl` stylesheet is used for this conversion. Make sure this feature is DataCite 4.5 compatible.

**Comment by jsjiang** [comment]
A side note:
OAI `harvest` and `GetRecord` call the `impl.datacite.upgradeDcmsRecord` function to upgrade DataCite Metadata Scheme to the latest version 4.x. Since the  `upgradeDcmsRecord` function was tested in the DC4.5 upgrade project. There is no need to test from OAI side.

```
    elif oaiRequest[1]["metadataPrefix"] == "datacite":
        me = impl.datacite.upgradeDcmsRecord(
            identifier.dataciteMetadata(), returnString=False
        )
```

**Comment by jsjiang** [comment]
Adam Buttrick:
I asked Maria about this and she provided the following context:
1. Initially, EZID only supported DataCite DOIs.
2. Later, we added Crossref support, but through an unusual process where Crossref DOIs were still somewhat treated as DataCite DOIs. This practice occurred before 2018.
3. Around 2018, Crossref informed EZID that this approach was no longer acceptable, so EZID discontinued it.
4. There may have been a conversion utility used in the past, but from her understanding, it hasn’t been in use since approximately 2019.
5. Since then, EZID has supported users switching from one DOI type to another, but not through an automated conversion process. Switching instead involves:
   - Transferring the prefix
   - Transferring the DOIs
   - Re-registering the DOIs with the correct metadata


Adam Buttrick:
So this may be legacy functionality that was used to convert Crossref format inputs to DataCite DOI format, which at the time was the only thing that could be registered?

**Comment by jsjiang** [comment]
Action:
* remove Crossref to DataCite conversion related code from EZID

**Comment by adambuttrick** [comment]
Moving action to new issue tagged here.
