### ISSUE TITLE
[FEATURE] OpenSearch monitoring with Nagios alerts

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#683]
**Describe the problem you would like to solve**
As part of transitioning EZID to OpenSearch, we need a reliable, automated way to monitor the operational status of OpenSearch in EZID. Specifically, we need a regular check to verify that this service is up and running.

**Describe the solution you'd like**
Implement a monitoring hook that checks the status of OpenSearch every 10 minutes. This hook would:
1. Ping a specified query URL/record we know always exists.
2. Verify that the expected return is received
3. If the check fails, trigger an alert

The monitoring hook should be integrated with Nagios, allowing us to use our existing monitoring and notifications.

**Who would benefit from this feature?**
- Developers: Ensures the availability of search in EZID and allows for rapid response troubleshooting in the event of a failure
- Users: Ensures the availability of search in EZID

**Additional information**
We need to determine and provide Ashley with the URL what it should return to set up the Nagios alert. The result returned from the URL would need to be static for the test to work correctly. Part of #653.

**Comment by adambuttrick** [comment]
Jing to provide URL from regression tests to use for this.

**Comment by sfisher** [comment]
Here is an easy url for testing retrieveal of 1 identifier: https://ezid.cdlib.org/search?filtered=t&identifier=ark%3A%2F13030%2Fm5z94194

**Comment by ashleygould** [comment]
I opened cdlsys request to update nagios: https://github.com/cdlib/cdlsys/issues/566

**Comment by ashleygould** [comment]
service checks are in place for stg and prd:
- uc3-ezid-ui-search-prd_7x16
- uc3-ezid-ui-search-stg_5x12
