### ISSUE TITLE
[FEATURE] Include the resolved URLs (Locations) in UI "Download All" functionality

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#688]
**Describe the problem you would like to solve**
Campus admins need a way to export the resolved URL (Location) for each DOI when downloading identifier metadata in bulk from the EZID Manage page in the UI. Currently, the "Download All" functionality does not include this information.

**Describe the solution you'd like**
The Download All feature on the https://ezid.cdlib.org/manage page should include the Location (URL) field for each DOI in the data dump. For example, for the DOI https://ezid.cdlib.org/id/doi:10.6075/J0474B2N, the dump should include its resolved URL: https://library.ucsd.edu/dc/object/bb78624124.

**Who would benefit from this feature?**
- Anyone working with large sets of records in the UI who needs to know their resolved URLs/locations

**Additional information**
Requested by UCSD.

**Comment by jsjiang** [comment]
* modified ezid-code (branch 688_add_location_url_to_download)
* need to update the API doc and the `batch-dwonload.sh` client tool to reflect this support

**Comment by jsjiang** [comment]
@adambuttrick Hi Adam,

This feature is ready on ezid-dev for testing. You can test it in two ways:

* Logon to EZID UI https://ezid-dev.cdlib.org/ , go to "Manage IDs" page, click "Download All"
* Use the `batch-download.sh` script in the `ezid-client-tool` repo. You would need to change the hostname from ezid to ezid-dev in the script. Here is sample command:

```
./batch-download.sh apitest apitest format=csv column=_id column=_mappedTitle co
lumn=_target notify=your_email_address
```

VPN is required to access ezid-dev.

Let me know if you have questions or notice any issues.

Thank you

Jing

**Comment by adambuttrick** [comment]
Tested batch download of existing API Test account data in the UI and using the bash script. Both returned data containing the the resolved URL (Location) for the identifiers. 

Created new record (doi:10.5072/FK2R212X88) in the UI (2024-08-07T19:18:59Z) and attempted batch download via UI and API, but newly created record was not immediately present in file. Proceeded to update record (2024-08-07T19:22:11Z) and was still not present in either download. Reattempted batch download via the UI (~2024-08-07T15:00:00Z) and record was returned with data containing the the resolved URL (Location) for the identifier.

I'm assuming the delayed availability in the batch download is a known issue resulting from the data moving around in the service, such that this is not a blocker for releasing the feature. It would be good to know/document what the expected delays are here, however.

**Comment by jsjiang** [comment]
@adambuttrick 
It is an asynchronous process.  We have following message on the UI after clicking on the "Download All" button. Should we update this message to make it clearer on the delays?

```
Download Request Received
Your download request is being processed and will be available in a few minutes.

When it is ready to download, an email with the download link will been sent to the email address affiliated with your EZID account: ezid@ucop.edu.

After you receive the email, you may also download a .csv file of the requested identifiers using the link below:

https://ezid-dev.cdlib.org/s3_download/t7a8CdMypfTl1x6A.zip

The download link will expire in 1 week.

```

**Comment by adambuttrick** [comment]
@jsjiang We can discuss further in standup. I think the more confusing aspect from a user perspective is that after we create an identifier (for any reason), if we navigate away from its page, we can't search and find it, either by its ID or metadata, for some unknown time period until it is populated in the corresponding tables, except by directly accessing it via URL. We flag in the UI that the DOI itself may take hours to resolve, but not this delay across different parts of the service. Whether this needs a specific call out in the UI or simply in documentation is something I'll think more about. 

 But from an acceptance criteria perspective, this is a non-issue and this feature appears otherwise ready to go!

**Comment by adambuttrick** [comment]
Added with https://github.com/CDLUC3/ezid/releases/tag/v3.2.17 and reviewed and approved by UCSD.
