### ISSUE TITLE
Fix OR query so it returns correct results in EZID OpenSearch

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#689]
The OR query doesn't currently operate at all.  Add some parsing to create the more complex query to "OR" words adjacent to the "OR" and AND everything else (since AND is the default).

In the future EZID may want to consider relevance ranking which is a typical way to use OpenSearch, but it conflicts with the way the entire current UI is really designed since results ranking puts most relevant results at the top and may return results without all words present.  Relevance ranking sorting conflicts with the strict column-based sorting we have now.

**Comment by sfisher** [comment]
Added commit ae310f2c0b60973c2b97f8b714084e67cd3bb05d to the bigger pull request which adds this functionality.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19
