### ISSUE TITLE
Limit SearchResult paging to 10,000 results

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#691]
After 10,000 records OpenSearch returns errors rather than giving more results for a query.  We think is OK, but it causes the UI to error for pages of results past this.

So . . . Limit the number of pages such as:

1,000 pages of 10 records per page.
100 pages of 100 records per page.
200 pages of 50 records per page.

This should prevent this error from happening.

**Comment by sfisher** [comment]
I modified the pager to only show up to 10,000 records while the number of results shows correctly still.

**Comment by adambuttrick** [comment]
Released with https://github.com/CDLUC3/ezid/releases/tag/v3.2.19
