### ISSUE TITLE
[TEST] Verify data fields updated by "link checker update" is updated in OpenSearch

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#703]
The `link checker update` job updates the `hasIssues` and `linkIsBroken` fields of an identifier in the`ezidapp_searchIdentifier` table. Make sure these updates are reflected in the OpenSearch index as well.

**Comment by jsjiang** [comment]
How to test:
* Option 1: start the `proc-link-checker-update` background job - this may or may not produce desired test datasets as we haven't run the link checker related jobs on ezid-stg for a while
* Option 2: manually update the `hasIssues` and `linkIsBroken` fields for a selected test identifiers.

**Comment by sfisher** [comment]
Thanks Jing,

I see that there is code to update these values in OpenSearch, also.  I'd be curious how you go about testing an item successfully updates values with the link checker.

Maybe we can do something like:

1. Set the values to their opposite in the database and opensearch manually for `hasIssues` and `linkIsBroken`.  I can do this pretty easily.
2. Run the link checker.
3. Check after the link checker is done to be sure values have been corrected for the items we changed.

Maybe you can point me toward how to run the link checker on stage where the OpenSearch code is currently running.  Is it just a proc- daemon that I can start from `cdlsysctl` or what is the best way to go about it?

**Comment by sfisher** [comment]
OK.  I've updated 5 items to be set to `hasIssues: True` and `linkIsBroken: True` which is the opposite of what they were before. It is these items:

```
ark:/13030/m5ps2hw4
ark:/88122/kxxw0099
ark:/88122/yjlx0083
ark:/13030/qt601312m8
doi:10.25345/C59R4D
```

![Screenshot 2024-08-13 at 3 14 40 PM](https://github.com/user-attachments/assets/ffd9f2ac-46af-48b9-b256-32efac51270c)

![Screenshot 2024-08-13 at 3 31 47 PM](https://github.com/user-attachments/assets/414d4ff1-2868-424a-924e-eb7852e5e2a1)

Then after we run the linkChecker it should revert these?

**Comment by sfisher** [comment]
The linkchecker ran last night and tool the steps that re-checked the failures and reset the items with `linkIsBroken=1` to `linkIsBroken=0` in both the database and in OpenSearch.  When it re-checks broken links it also re-checks the `hasIssues` flag and reset it.  (We tried one with just `hasIssues=1` and the link checker doesn't seem to recheck these and neither changed in the DB or in OpenSearch).

![Screenshot 2024-08-14 at 9 54 15 AM](https://github.com/user-attachments/assets/5b1989fe-495f-475c-b14c-0e73be1dfe64)

![Screenshot 2024-08-14 at 9 55 48 AM](https://github.com/user-attachments/assets/cc18ff4f-7593-4b03-beed-36632ad83dc5)

I believe we can call this working.

**Comment by adambuttrick** [comment]
Test passed as part of release https://github.com/CDLUC3/ezid/releases/tag/v3.2.19
