### ISSUE TITLE
Step-by-step deploy and config of ezid

### ISSUE THREAD

**Issue by asidibe1** [CDLUC3/ezid#706]
Hi,
Thank you for all your effort in this great project. However, the information are a bit sparse and structured specially for non specialists. Is it possible to have a clear step-by-step guideline for installing or deploying ezid on a ubuntu server, docker or any kind?
Your help is really appreciated.
Best regards
Adama

**Comment by adambuttrick** [comment]
The complexity and specificity of EZID's codebase, in addition to its infrastructure requirements, means that it is not terribly well-suited to the more basic use case of getting started with minting and resolving ARKs. While it may be possible to do build and deploy elsewhere, our focus is on supporting the service's existing users within the context of our infrastructure. Members of the [ARKs Alliance](https://arks.org/) can hopefully provide examples of other/easier ways to get started with this work.

**Comment by asidibe1** [comment]
Thank you for your reply.
Best
