### ISSUE TITLE
[BUG] API Registration Conflicts with UI Validation

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#708]
**Describe the bug**
Metadata will register successfully in EZID via the API, despite the same version failing validation when submitted through the UI. Specifically, UI invalid language tagging in the Title Language field is validated or required to conform to the same constraints in API submissions.

**To Reproduce**
1. Prepare DataCite metadata with invalid language tagging (e.g., "en-us" instead of "en-US") in the Title Language fields.
2. Submit this metadata via the EZID API to register a new DOI.
3. Observe that the registration is successful, despite the invalid metadata.
4. Attempt to register the same metadata through the EZID UI.
5. Observe that the UI registration fails due to the invalid language tagging.

**Expected behavior**
The API should validate the DataCite metadata, including language tags, before allowing registration. It should reject submissions with invalid metadata, consistent with the behavior in the UI.

**Additional context**
1. This issue was first reported in relation to https://ezid.cdlib.org/id/doi:10.25345/C5M902D88 failing to register a DataCite DOI, as reported by UCSD.
2. Specific problem is the use of lowercase "en-us" where IETF BCP 47 requires "en-US".
3. Tested registration of the same metadata on the staging environment (https://ezid-stg.cdlib.org/id/doi:10.5072/FK25R10B9G2) and confirmed that the API returns success with invalid metadata.
4. Tested registration of the same metadata with the title language set to "en-us" in the UI and registration fails as expected.
5. Note: Validation of IETF BCP 47 appears to only occur for certain fields. Other fields in https://ezid.cdlib.org/id/doi:10.25345/C5M902D88 are tagged with "en-us" as their language and do not result in errors.

**Comment by jsjiang** [comment]
DOIs from shoulder (10.25345/C5) that have a failed registration status (56 total):
```
doi                                             Error                                                 Enqueue time
doi:10.25345/C5639K959	The read operation timed out	2022-12-01 06:44:48
doi:10.25345/C5XP6V79W	HTTP Error 500: Internal Server Error	2022-12-01 15:45:47
doi:10.25345/C5FN10X50	HTTP Error 502: Bad Gateway	2022-12-21 11:16:14
doi:10.25345/C51C1TM5D	HTTP Error 502: Bad Gateway	2022-12-21 14:32:42
doi:10.25345/C5V11VR3N	HTTP Error 502: Bad Gateway	2022-12-21 15:18:47
doi:10.25345/C5RR1PS2V	HTTP Error 502: Bad Gateway	2022-12-21 15:43:29
doi:10.25345/C5V97ZX4N	HTTP Error 502: Bad Gateway	2022-12-21 17:07:02
doi:10.25345/C5BN9X81T	HTTP Error 502: Bad Gateway	2022-12-21 21:02:27
doi:10.25345/C59C6S631	HTTP Error 502: Bad Gateway	2022-12-21 21:27:12
doi:10.25345/C5FX7440Z	HTTP Error 502: Bad Gateway	2022-12-21 21:33:37
doi:10.25345/C55H7C05V	HTTP Error 502: Bad Gateway	2022-12-21 21:36:19
doi:10.25345/C5GT5FM8B	HTTP Error 502: Bad Gateway	2022-12-21 21:40:55
doi:10.25345/C57941092	HTTP Error 502: Bad Gateway	2022-12-21 21:41:33
doi:10.25345/C5QB9VB54	HTTP Error 502: Bad Gateway	2022-12-21 21:42:46
doi:10.25345/C5FT8DQ83	HTTP Error 502: Bad Gateway	2022-12-21 21:43:40
doi:10.25345/C5697039T	HTTP Error 502: Bad Gateway	2022-12-21 21:43:58
doi:10.25345/C5PC2TF7D	HTTP Error 502: Bad Gateway	2022-12-21 21:45:11
doi:10.25345/C5930P13H	HTTP Error 502: Bad Gateway	2022-12-21 21:46:25
doi:10.25345/C5833N438	HTTP Error 502: Bad Gateway	2022-12-21 21:49:47
doi:10.25345/C5VX0684K	HTTP Error 502: Bad Gateway	2022-12-21 21:50:41
doi:10.25345/C5MC8RN4G	HTTP Error 502: Bad Gateway	2022-12-21 21:51:17
doi:10.25345/C5GM81V0Q	HTTP Error 502: Bad Gateway	2022-12-21 21:52:32
doi:10.25345/C5736M74H	HTTP Error 502: Bad Gateway	2022-12-21 21:52:33
doi:10.25345/C5FN10Z1H	HTTP Error 502: Bad Gateway	2022-12-21 21:53:46
doi:10.25345/C59W0948N	HTTP Error 502: Bad Gateway	2022-12-21 21:54:21
doi:10.25345/C5XP6V87C	HTTP Error 502: Bad Gateway	2022-12-21 21:55:16
doi:10.25345/C5SX64G3M	HTTP Error 502: Bad Gateway	2022-12-21 21:55:16
doi:10.25345/C5DN40225	HTTP Error 502: Bad Gateway	2022-12-21 21:56:16
doi:10.25345/C5348GN5K	HTTP Error 502: Bad Gateway	2022-12-21 23:12:34
doi:10.25345/C5NS0M40K	HTTP Error 502: Bad Gateway	2022-12-21 23:27:13
doi:10.25345/C5542JG03	HTTP Error 502: Bad Gateway	2022-12-22 10:03:14
doi:10.25345/C5FT8DS61	HTTP Error 502: Bad Gateway	2022-12-23 23:34:15
doi:10.25345/C50000771	HTTP Error 502: Bad Gateway	2022-12-24 01:19:17
doi:10.25345/C5377639P	HTTP Error 502: Bad Gateway	2022-12-24 07:13:53
doi:10.25345/C5M32NJ8S	HTTP Error 502: Bad Gateway	2022-12-24 07:23:29
doi:10.25345/C5NS0M67V	HTTP Error 502: Bad Gateway	2022-12-29 22:04:07
doi:10.25345/C5HX1607Q	HTTP Error 502: Bad Gateway	2022-12-29 22:24:41
doi:10.25345/C59P2WF9W	HTTP Error 502: Bad Gateway	2022-12-30 00:39:56
doi:10.25345/C5PK07B6V	HTTP Error 502: Bad Gateway	2023-01-24 08:31:42
doi:10.25345/C55Q4RS83	HTTP Error 502: Bad Gateway	2023-02-24 13:27:32
doi:10.25345/C5707WZ2M	HTTP Error 502: Bad Gateway	2023-02-24 13:33:08
doi:10.25345/C5XW48598	The read operation timed out	2023-03-23 09:30:28
doi:10.25345/C5K64B34S	The read operation timed out	2023-04-04 02:29:35
doi:10.25345/C59P2WG7C	The read operation timed out	2023-04-04 04:40:29
doi:10.25345/C55X25P43	The read operation timed out	2023-04-04 05:05:19
doi:10.25345/C5T727R78	The read operation timed out	2023-04-14 07:53:30
doi:10.25345/C51Z4237J	The read operation timed out	2023-06-01 08:57:01
doi:10.25345/C5X63BG2G	The read operation timed out	2023-06-01 09:19:07
doi:10.25345/C5SF2MN6R	The read operation timed out	2023-06-01 09:28:08
doi:10.25345/C5NP1WV14	The read operation timed out	2023-06-01 10:37:53
doi:10.25345/C5HX16175	The read operation timed out	2023-06-01 12:59:47
doi:10.25345/C5D795M7K	HTTP Error 503: Service Unavailable	2023-06-01 15:52:12
doi:10.25345/C58G8FT4X	HTTP Error 503: Service Unavailable	2023-06-01 19:28:31
doi:10.25345/C5VT1H150	The read operation timed out	2024-03-13 03:28:34
doi:10.25345/C5R20S72N	HTTP Error 500: Internal Server Error	2024-03-13 04:55:19
doi:10.25345/C5M902D88	HTTP Error 500: Internal Server Error	2024-03-13 06:15:37
```

**Comment by jsjiang** [comment]
It looks like EZID UI only validate language code for the following fields:
* title
* subject
* description

The validation is done using a regular express: 
```
REGEX_LANGUAGE = '^[a-z]{2,3}(?:-[A-Z]{2,3}(?:-[a-zA-Z]{4})?)?$'
```

From ChatGPT:

The regular expression matches strings that:
* Start with a 2- or 3-letter lowercase language code (e.g., "en" or "fra").
* Optionally followed by a hyphen and a 2- or 3-letter uppercase region code (e.g., "-US" or "-GB").
* Optionally followed by another hyphen and a 4-letter script code that can be in lowercase or * uppercase (e.g., "-Latn").
* The entire string must match the pattern from start to finish.

Examples of Valid Matches:
- en
- fr
- en-US
- fr-CA
- zh-Hans
- sr-Cyrl

Examples of Invalid Matches:

- EN (uppercase, but the first part should be lowercase)
- en-us (region part should be uppercase)
- en-US-Lat (last part should be exactly 4 letters)

**Comment by adambuttrick** [comment]
Since we have an assorted set of errors, one thing we should verify is whether the 500 errors were the result of attempting to register with the language codes in this format or something else. I looked at doi:10.25345/C5R20S72N and doi:10.25345/C5M902D88 (two most recent entries with HTTP Error 500 errors) in the UI and both had the language code issue. Because you can register via the EZID API, but not in the DataCite API, it's also not clear from our current implementation that EZID's validation and DataCite validation are completely or correctly aligned.

**Comment by adambuttrick** [comment]
Spoke with DataCite contact and both "en-us" and "en-US" are valid, so our existing UI constraint is not consistent with their schema and should not be in place. The failed registration was the result of a system outage that occurred between 2024-03-13 01:15:39 UTC and 2024-03-13 10:25:38. While from https://github.com/CDLUC3/ezid/issues/696, it's not clear that we have any retry logic to account for such failures, they subsequently could not be registered via the UI because of the language code validation conflict. Since the UI constraint on the language codes is invalid, closing this issue and creating a new one to remove the UI constraint.
