### ISSUE TITLE
[MAINTENANCE] proc-cleanup-async-queues improvements

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#727]
**Service/repository**
EZID - `proc-cleanup-async-queues.py` script

**Describe the current state/issue**

As described in https://github.com/CDLUC3/ezid/issues/723, the current proc-cleanup-async-queues.py script has some limitations that prevent proper queue clearing. It is currently constrained by a batch size of 100, which appears to be leading to missed records when the processing time range contains more than this is the allowed time range. Relative to this, the current 2-week processing window may not be optimal for cleanup. The script also generally lacks the flexibility to handle potential status changes in other queues and record types, limiting its adaptability to the task queue redesign on #707. Inadequate logging also makes it difficult to identify issues or track unprocessed records effectively.

**Describe the desired state/solution**
An optimized `proc-cleanup-async-queues.py` script that:

1. Handles both "S" and "O" statuses for successful processing in the DataCite queue, accounting for the change that occurred on June 29, 2023.

2. Includes logic to handle potential status changes in other queues to future-proof the script.

3. Has an adjustable and optimized time window for processing, which can be easily configured based on each queue's needs. Processes all records within the time range, regardless of the number, either by handling larger batches or implementing an alternate means to ensure complete queue processing.

4. Currently the time window is the past week. The records are selected by updated timestamp and ordered by the primary key in descending order. This means the most recently updated records are deleted first. This might not be the initial plan. We probably want to keep most recently processed records for 1-2 weeks before deleting them from the queues (Confirm with the team).

5.  Processes all records within the time range, regardless of the number, either by handling larger batches or implementing an alternate means to ensure complete queue processing.

6. Provides logging/reporting to identify unprocessed records.

**Comment by jsjiang** [comment]
Work order:
4. Has an adjustable and optimized time window for processing, which can be easily configured based on each queue's needs.
5. Keep most recently processed records in all status for 2 weeks before deleting the successfully processed records from the queues
3. Processes all records within the time range, regardless of the number of qualified records

**Comment by jsjiang** [comment]
Checklist:
- [ ] define time window from and to timestamps as optional command options
- [ ] define batch size as an optional command option - find out a  best performaning batch size and set it as the default batch size
- [ ] log deleted identifiers when running the cleanup async queues in debugging mode
- [ ] Keep most recently processed records in all status for 2 weeks before deleting the successfully processed records from the queues
- [ ] Processes all records within the time range, regardless of the number of qualified records

**Comment by jsjiang** [comment]
Tested the `proc-cleanup-async-queues_v2.py` script against the DEV database (10/23)
* date range: between 20220405 and 20220406 
* records selected from the refIdentifier table: 319 records selected
* matched records in the datacite queue:
  * before running script: 319
  * after running script: 319 (all with status="F"
* matched records in the crossref queue:
  * before running the script: 319
  * after running the script: 0
 * matched records in the searchIndexrere queue:
  * before running the script: 319
  * after running the script: 0
 
```
# before running new async script: 319
# after running new async script: 319
select id, identifier, from_unixtime(createTime), from_unixtime(updateTime) from ezidapp_refidentifier 
where from_unixtime(updateTime) between '2022-04-05' and  '2022-04-06';

# before running new async script: 95077 
# after running new async script: 95077 
select count(id) from ezidapp_refidentifier;

# before: 159035
# after: 159035
select count(seq) from ezidapp_datacitequeue;

# before: 159035
# after:  158716 (reduced 319)
select count(seq) from ezidapp_crossrefqueue;

# before: 774270
# after:  773951 (reduced 319)
select count(seq) from ezidapp_searchindexerqueue;

# 319 records remained after the running the cleanup script; all with status=F
select *, from_unixtime(enqueueTime), from_unixtime(submitTime) from ezidapp_datacitequeue 
where refidentifier_id in (
select id from ezidapp_refidentifier 
where from_unixtime(updateTime) between '2022-04-05' and  '2022-04-06');

# before: 319; after: 0
select *, from_unixtime(enqueueTime), from_unixtime(submitTime) from ezidapp_crossrefqueue 
where refidentifier_id in (
select id from ezidapp_refidentifier 
where from_unixtime(updateTime) between '2022-04-05' and  '2022-04-06');

# before: 319; after: 0
select *, from_unixtime(enqueueTime), from_unixtime(submitTime) from ezidapp_searchindexerqueue 
where refidentifier_id in (
select id from ezidapp_refidentifier 
where from_unixtime(updateTime) between '2022-04-05' and  '2022-04-06');

python manage.py proc-cleanup-async-queues_v2 --updated_from 20220405 --updated_to 20220406
```

**Comment by adambuttrick** [comment]
Deployed proc-cleanup-async-queues_v2.py on ezid-prd on Oct 30 with release v3.2.27

**Comment by jsjiang** [comment]
* Deployed `proc-cleanup-async-queues_v2.py` on EZID-PRD Oct 30 with release `v3.2.27`

**Comment by jsjiang** [comment]
* Replaced `proc-cleanup-async-queues.py` with `proc-cleanup-async-queues_v2.py` in branch `test-async-cleanup-v2`
* Testing `proc-cleanup-async-queues.py` with default settings (started by the deployment script without input paramters) on ezid-stg
*

**Comment by jsjiang** [comment]
* Deployed refactored `proc-cleanup-async-queues.py` in `v3.2.30` on Dec 4
* The `ezid-proc-cleanup-async-queues` is up and running
  * have processed the qualified records in the initial date/time range between "2024-11-06T07:19:17 and 2024-11-20T07:19:17"
  * the job is moving processing window one hour since then for each batch
  * processed records: 
    * before: 1559 records between '2024-11-17' and "2024-11-20" (missed by previous `proc-cleanup-async-queues.py` job)
    * after: 58 records 
    * processed records: 1559

Log entries:
```
ezid@uc3-ezidui-prd01:07:19:16:~/logs/background_jobs$ sudo cdlsysctl status  ezid-proc-cleanup-async-queues
● ezid-proc-cleanup-async-queues.service - EZID Background Job proc-cleanup-async-queues
     Loaded: loaded (/etc/systemd/system/ezid-proc-cleanup-async-queues.service; enabled; preset: disabled)
     Active: active (running) since Wed 2024-12-04 07:19:16 PST; 3s ago
   Main PID: 95640 (python)
      Tasks: 1 (limit: 9238)
     Memory: 75.3M
        CPU: 834ms
     CGroup: /system.slice/ezid-proc-cleanup-async-queues.service
             └─95640 /ezid/.pyenv/versions/ezid-py311/bin/python /ezid/ezid/manage.py proc-cleanup-async-queues
 
Dec 04 07:19:16 uc3-ezidui-prd01 systemd[1]: Started ezid-proc-cleanup-async-queues.service - EZID Background Job proc-cleanup-async-queues.
Dec 04 07:19:17 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:     INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Checking ref Ids: updated between: 2024-11-06T07:19:17 and 2024-11-20T07:19:17, filter: (AND: ('>

 ezid@uc3-ezidui-prd01:10:45:14:~/logs/background_jobs$ grep async ezid-proc-error.log | grep 95640 | more
Dec  4 08:19:24 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Checking ref Ids: updated between: 2024-11-20T07:19:17 and 2024-11-20T
08:19:24, filter: (AND: ('updateTime__gte', 1732115957), ('updateTime__lte', 1732119564), ('id__gt', 0))
Dec  4 08:19:31 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Checking ref Ids returned: 0 records
Dec  4 08:19:31 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Sleep 3600 seconds before processing next time range.
Dec  4 09:19:31 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Checking ref Ids: updated between: 2024-11-20T08:19:24 and 2024-11-20T
09:19:31, filter: (AND: ('updateTime__gte', 1732119564), ('updateTime__lte', 1732123171), ('id__gt', 0))
Dec  4 09:19:38 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Checking ref Ids returned: 0 records
Dec  4 09:19:38 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Sleep 3600 seconds before processing next time range.
Dec  4 10:19:38 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Checking ref Ids: updated between: 2024-11-20T09:19:31 and 2024-11-20T
10:19:38, filter: (AND: ('updateTime__gte', 1732123171), ('updateTime__lte', 1732126778), ('id__gt', 0))
Dec  4 10:19:44 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Checking ref Ids returned: 0 records
Dec  4 10:19:44 uc3-ezidui-prd01 ezid-proc-errorlog[95640]:    INFO ezidapp.management.commands.proc-cleanup-async-queues 140451843716928: Sleep 3600 seconds before processing next time range.
```

Records processed:
```
# reduced from 1617 -> 58 records
select *, from_unixtime(createtime), from_unixtime(updatetime) from ezidapp_refidentifier
where updatetime between unix_timestamp('2024-11-17') and unix_timestamp("2024-11-20")
and crossrefStatus !='F';
```
