### ISSUE TITLE
Check and update cron jobs after production cutover

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#74]
[EZID-PROD ~] crontab -l
SHELL=/bin/bash
PATH=/apps/ezid/sw/bin:/bin:/usr/bin
MAILTO=marisa.strong@ucop.edu,maria.gould@ucop.edu,rushiraj.nenuji@ucop.edu
PYTHONPATH=/apps/ezid/apps/apache/ezid/SITE/PROJECT
DJANGO_SETTINGS_MODULE=settings.production

# Backups
0 * * * * /apps/ezid/apps/apache/ezid/SITE/logs/hourly-backup
0 2 * * * /apps/ezid/backups/daily

# Nightly maintenance
0 0 * * * /apps/ezid/apps/apache/ezid/SITE/PROJECT/tools/expire-downloads
5 0 * * * /apps/ezid/apps/apache/bin/log-rotation-support

# Sunday morning maintenance
0 0 * * 0 django-admin clearsessions
10 0 * * 0 /apps/ezid/apps/apache/ezid/SITE/PROJECT/tools/expunge

**Comment by rushirajnenuji** [comment]
List of tasks:

### Production Environment

- [ ] Cron job for transaction logs: Copy and preserve historical logs to the new production instance.
- [ ] Cron job for transaction logs: Update the job `hourly-backup` and place it on the new instance.
- [ ] Cron job for daily backups: Set up ssh access for prod instance to start replicating backups on the stagging instance
