### ISSUE TITLE
Update code to ensure sure updateTime updated w/ link checker

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/ezid#752]
Jing and I talked about this in our dev sync.

We tested to be sure updates to metadata are updated in the SearchIdentifier updateTime.  They are updated correctly.

The remaining place to update is in the link checker which isnt currently updating this time.

**Comment by adambuttrick** [comment]
Released with [v3.2.28](https://github.com/CDLUC3/ezid/releases/tag/v3.2.28).
