### ISSUE TITLE
wishlist for EZID infrastructure and hosting improvements

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/ezid#78]
This is a set of conversation topics on how we can make the ezid service more robust and easier to migrate and deploy.

Goals
- ability to reprovision new ezid ui hosts quickly and accurately
- ability to run ezid ui on multiple instances
- ability to stop/start individual ezid ui instances without interrupting the service
- automate everything!
- immutable architecture - no need to ever log onto host systems
- continuous deployment
- aspire to meet the Twelve-Factor App methodology: https://12factor.net/

migration
- build ezid ui as a pip package
- fully automate ezid ui installation and configuration
- fully automate ezid ui deployments

configuration
- run ezid under uwsgi
- rely on systemd unit file to manage service - no intermediate shell script
- remove any references to dns hostnames or ip addresses from configs
- remove any hardcoded file paths or usernames from configs
- make use of environment vars or ssm params to supply config options at deploy time

hosting
- offload cronjobs to some kind of dedicate batch processing service
- offload BDB database to a service, not local
- offload logging to a service - centralized logging
- log streaming direct to S3 for EZID app transaction logs
- tighten firewall (ec2 securitygroup) rules for ec2 instance to only allow access to port 18880 from the loadbalancer.
- build out docker instance for development environments
- run ezid ui in ECS with autoscaling

Typical Scope for IAS
- All things AWS:
   - create new EC2 instances
   - update EC2 instance profiles (iam permissions)
   - create RDS instances
   - configure networking
      - DNS
      - Routing
      - firewall access (ec2 security groups)
   - configure ALBs
- generate SSL certs
- configure Nagios alerting
- provision user access
- manage sudo privs

Typical Scope of UC3OPS
- provision services on new ec2 instances
   - install software
   - set up application directories
   - initial application deployment
- patch system software
- configuration management:
   - init scripts
   - crontabs
   - application role account environment
- service monitoring and performance tuning

**Comment by ashleygould** [comment]
I've created new git issues covering much of these aspirations.  The text of this issue can probably get buried in a wiki some where.

**Comment by mariagould** [comment]
Closing per Ashley's comment Feb 2
