### ISSUE TITLE
Begin exploring splunk and determine if we can/should use it for logging

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#81]
Check with IAS about availability & pricing (Marisa to do)

**Comment by mariagould** [comment]
Update December 15: Ashley & Marisa discussed with IAS. IAS has decided that they will not be moving forward with Splunk. Permissions model is very complex and requires significant resources to support. 

Alternative is to explore Elasticsearch and Cabana. Ashley to follow up.

**Comment by marisastrong** [comment]
https://www.elastic.co/kibana
