### ISSUE TITLE
Re-evaluate and document approach to handling application transaction logs (not DB logs)

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/ezid#93]
Refers to application transaction logs that we currently back up on stage (as a substitute for prior arrangement with EDINA) through hourly rsync. 

Question: Do we still need to retain these logs? If so, for how long?

**Comment by marisastrong** [comment]
**Note** the term transaction does not refer to database transactions,  rather application operations

**Transactions and error recovery**
An EZID identifier operation often involves executing multiple sub-operations on different, remote systems. If a failure occurs anywhere, there is no means of rolling back the operation as a whole; EZID operations are not ACID-compliant. To mitigate this shortcoming, EZID wraps operations in a lightweight form of transactions, specifically, it logs transaction "BEGIN" and "END" records and in-transaction "PROGRESS" records. A transaction that ends in an error must be examined to determine which sub-operations succeeded and which didn't, and from there the operation will need to be manually fixed up.

When archiving rolled-over transaction logs (Hourly:
(production only) The transaction log is copied to the uc3-ezid-ui-stg host), be sure to check for errors first. The archival process removes all failed transactions and progress records.

The Apache stop and restart commands, and the EZID reload operation, all pause the system and wait until it is idle to ensure that no transactions are cut off in the middle.

There are several tools in the .../ezid/tools directory that can be used to check internal and cross-database consistency: diff-dumps, diff-ezid-mds, and verify-dump.

- [ ] Does the archival/copy cron job remove failed transactions?  
- [ ] Do we  need to archive this for longer than 24 hours?  i.e. Can we rely on the EC2 daily backups for logs prior to 24 hours?

**Comment by marisastrong** [comment]
This is related to issue https://github.com/CDLUC3/ezid-service/issues/121

**Comment by marisastrong** [comment]
decided to no longer archive the transaction logs on the stage server.  Ashley will remove the cron job.  The logs will still live on the prod server 
- [ ] @ashleygould create a ticket to manage the logs on prod (logrotate, etc)

**Comment by mariagould** [comment]
Closing this one and will be following up via #124 and #125
