### ISSUE TITLE
Host public downloads on EFS

### ISSUE THREAD

**Issue by ashleygould** [CDLUC3/ezid#99]
To avoid hosting application data on local storage, we should mount `/apps/ezid/var/www/download/public` on a shared filesystem such as EFS.
Alternatively, we can explore using S3 object store for hosting public downloads.

**Comment by rushirajnenuji** [comment]
Sub task:

- [ ] fix the download expunge script to remove download files after a week from the new storage location (EFS / S3 object store / ...)

**Comment by jsjiang** [comment]
Completed. See related ticket and pull request:
#521 
#566
